In [4]:
from shining_pebbles import *
from crypto_etl import *

In [47]:
def extract_datetime_str_from_filename(file_name:str)->str:
    return file_name.split('at')[-1].split('.csv')[0]

DATASET_BINANCE_PREFIX = 'dataset-binance_api-at'
file_names = scan_files_including_regex(file_folder=FILE_FOLDER['binance'], regex=DATASET_BINANCE_PREFIX)
datetime_strs = [extract_datetime_str_from_filename(file_name) for file_name in file_names]
datetime_strs

['2025-09-22 14:12:15.558889',
 '2025-09-22 14:36:51.024951',
 '2025-09-22 15:13:32.437206',
 '2025-09-22 15:13:42.324450',
 '2025-09-22 15:13:44.929049',
 '2025-09-22 15:13:57.197217',
 '2025-09-22 15:14:04.108237',
 '2025-10-01 10:45:39.493475',
 '2025-10-01 10:45:43.572308',
 '2025-10-01 10:45:45.038490',
 '2025-10-01 10:45:45.870827',
 '2025-10-01 10:45:47.456667',
 '2025-10-01 10:45:49.275929',
 '2025-10-01 10:45:50.254635',
 '2025-10-01 10:45:51.168384',
 '2025-10-01 10:45:52.072152',
 '2025-10-01 10:45:52.998195',
 '2025-10-01 10:45:53.817472',
 '2025-10-01 10:45:54.834691',
 '2025-10-01 10:45:55.687214',
 '2025-10-01 10:53:32.732888',
 '2025-10-01 11:05:53.034961',
 '2025-10-01 11:06:03.214001',
 '2025-10-01 11:06:13.409766',
 '2025-10-01 11:06:23.615444',
 '2025-10-01 11:06:33.816770',
 '2025-10-01 11:06:43.976897',
 '2025-10-01 11:06:54.164687',
 '2025-10-01 11:07:04.324132',
 '2025-10-01 11:07:14.526111',
 '2025-10-01 11:07:24.709910',
 '2025-10-01 11:07:34.936393',
 '2025-10-01 11:07:45.100529',
 '2025-10-01 11:07:55.360115',
 '2025-10-01 11:08:05.536255',
 '2025-10-01 11:08:15.699199',
 '2025-10-01 11:08:25.890581',
 '2025-10-01 11:08:36.065507',
 '2025-10-01 11:08:46.212176',
 '2025-10-01 11:08:56.360178',
 '2025-10-01 11:09:06.545494',
 '2025-10-01 11:09:16.732794',
 '2025-10-01 11:09:26.874669',
 '2025-10-01 11:09:37.042067',
 '2025-10-01 11:09:47.210575',
 '2025-10-01 11:09:57.382201',
 '2025-10-01 11:10:07.535110',
 '2025-10-01 11:10:17.690720',
 '2025-10-01 11:10:27.850876',
 '2025-10-01 11:10:38.097263',
 '2025-10-01 11:10:48.275960',
 '2025-10-01 11:10:58.474196',
 '2025-10-01 11:11:08.609383',
 '2025-10-01 11:11:18.755025',
 '2025-10-01 11:11:28.888563',
 '2025-10-01 11:11:39.056709',
 '2025-10-01 11:11:49.191821',
 '2025-10-01 11:14:00.669660',
 '2025-10-01 11:14:11.330199',
 '2025-10-01 12:37:09.941490',
 '2025-10-01 12:37:20.414823',
 '2025-10-01 12:49:09.240350',
 '2025-10-01 12:49:19.558931',
 '2025-10-01 12:49:29.768361',
 '2025-10-01 12:49:39.943969',
 '2025-10-01 12:56:40.983929',
 '2025-10-01 12:56:51.322061',
 '2025-10-01 12:57:01.679620',
 '2025-10-01 12:57:11.875653',
 '2025-10-01 12:58:04.037209',
 '2025-10-01 12:58:14.405660',
 '2025-10-01 12:58:24.622651',
 '2025-10-01 12:58:34.853284',
 '2025-10-01 12:58:46.390962',
 '2025-10-01 12:58:56.586105',
 '2025-10-01 12:59:06.757927',
 '2025-10-01 12:59:16.924617',
 '2025-10-01 13:01:00.718376',
 '2025-10-01 13:01:11.232469',
 '2025-10-01 13:01:42.075645',
 '2025-10-01 13:01:52.443548',
 '2025-10-01 13:02:02.931495',
 '2025-10-01 13:02:13.111562',
 '2025-10-01 13:03:10.701921',
 '2025-10-01 13:03:21.083706',
 '2025-10-01 13:03:31.544246',
 '2025-10-01 13:03:42.660240',
 '2025-10-01 13:03:53.399241',
 '2025-10-01 13:04:04.793570',
 '2025-10-01 13:04:15.057347',
 '2025-10-01 13:04:25.279739',
 '2025-10-01 13:04:38.869161',
 '2025-10-01 13:04:49.501548',
 '2025-10-01 13:04:59.957084',
 '2025-10-01 13:05:10.399347',
 '2025-10-01 13:05:21.996818',
 '2025-10-01 13:05:32.198062',
 '2025-10-01 13:05:42.751156',
 '2025-10-01 13:05:53.092701',
 '2025-10-01 13:06:03.879166',
 '2025-10-01 13:06:14.711475',
 '2025-10-01 13:06:24.964406',
 '2025-10-01 13:06:37.947457',
 '2025-10-01 13:06:48.888449',
 '2025-10-01 13:07:00.697791',
 '2025-10-01 13:07:11.733244',
 '2025-10-01 13:07:21.994082',
 '2025-10-01 13:07:32.742785',
 '2025-10-01 13:07:42.993502',
 '2025-10-01 13:07:53.375453',
 '2025-10-01 13:08:05.647416',
 '2025-10-01 13:08:16.001365',
 '2025-10-01 13:08:50.876704',
 '2025-10-01 13:09:02.637033',
 '2025-10-01 13:09:13.391309',
 '2025-10-01 13:09:24.675636',
 '2025-10-01 13:09:35.939977',
 '2025-10-01 13:09:47.658174',
 '2025-10-01 13:09:58.898394',
 '2025-10-01 13:10:09.483793',
 '2025-10-01 13:10:24.809651',
 '2025-10-01 13:10:35.137401',
 '2025-10-01 13:10:45.930968',
 '2025-10-01 13:10:56.413773',
 '2025-10-01 13:11:06.673597',
 '2025-10-01 13:11:19.665754',
 '2025-10-01 13:11:29.928015',
 '2025-10-01 13:11:40.473656',
 '2025-10-01 13:11:50.608421',
 '2025-10-01 13:12:02.235946',
 '2025-10-01 13:12:12.508934',
 '2025-10-01 13:12:23.028914',
 '2025-10-01 13:12:34.221298',
 '2025-10-01 13:12:44.741413',
 '2025-10-01 13:12:56.744041',
 '2025-10-01 13:13:09.419102',
 '2025-10-01 13:13:20.121904',
 '2025-10-01 13:13:31.331059',
 '2025-10-01 13:13:41.697555',
 '2025-10-01 13:13:52.448531',
 '2025-10-01 13:14:02.975175',
 '2025-10-01 13:14:14.764309',
 '2025-10-01 13:14:25.006507',
 '2025-10-01 13:14:38.917103',
 '2025-10-01 13:14:56.407622',
 '2025-10-01 13:15:06.717935',
 '2025-10-01 13:15:16.955800',
 '2025-10-01 13:15:27.247958',
 '2025-10-01 13:15:40.355286',
 '2025-10-01 13:15:50.596524',
 '2025-10-01 13:16:01.026622',
 '2025-10-01 13:16:12.339518',
 '2025-10-01 13:16:22.584045',
 '2025-10-01 13:16:32.821317',
 '2025-10-01 13:16:45.769997',
 '2025-10-01 13:16:57.964636',
 '2025-10-01 13:17:09.329148',
 '2025-10-01 13:17:20.610012',
 '2025-10-01 13:17:32.050028',
 '2025-10-01 13:17:43.410994',
 '2025-10-01 13:17:53.675885',
 '2025-10-01 13:18:04.348068',
 '2025-10-01 13:18:14.659651',
 '2025-10-01 13:18:24.900409',
 '2025-10-01 13:18:35.794689',
 '2025-10-01 13:18:46.211239',
 '2025-10-01 13:18:56.425553',
 '2025-10-01 13:19:06.783184',
 '2025-10-01 13:19:17.085056',
 '2025-10-01 13:19:27.331126',
 '2025-10-01 13:19:37.700378',
 '2025-10-01 13:19:48.351050',
 '2025-10-01 13:19:58.557340',
 '2025-10-01 13:20:09.029776',
 '2025-10-01 13:20:19.241419',
 '2025-10-01 13:20:29.517433',
 '2025-10-01 13:20:39.704556',
 '2025-10-01 13:20:50.948142',
 '2025-10-01 13:21:01.313176',
 '2025-10-01 13:21:11.613412',
 '2025-10-01 13:21:21.855786',
 '2025-10-01 13:21:33.083827',
 '2025-10-01 13:21:44.912438',
 '2025-10-01 13:21:55.142309',
 '2025-10-01 13:22:05.450054',
 '2025-10-01 13:22:15.705951',
 '2025-10-01 13:22:26.290765',
 '2025-10-01 13:22:38.163255',
 '2025-10-01 13:22:48.687247',
 '2025-10-01 13:22:59.031961',
 '2025-10-01 13:23:09.681310',
 '2025-10-01 13:23:20.962303',
 '2025-10-01 13:23:32.003246',
 '2025-10-01 13:23:42.263401',
 '2025-10-01 13:23:54.560381',
 '2025-10-01 13:24:05.002567',
 '2025-10-01 13:24:15.170624',
 '2025-10-01 13:24:25.922627',
 '2025-10-01 13:24:36.165524',
 '2025-10-01 13:24:46.371683',
 '2025-10-01 13:24:56.617571',
 '2025-10-01 13:25:08.406880',
 '2025-10-01 13:25:19.146565',
 '2025-10-01 13:25:29.881586',
 '2025-10-01 13:25:41.210395',
 '2025-10-01 13:25:51.489172',
 '2025-10-01 13:26:01.764209',
 '2025-10-01 13:26:12.298378',
 '2025-10-01 13:26:23.818827',
 '2025-10-01 13:26:34.120249',
 '2025-10-01 13:26:46.147817',
 '2025-10-01 13:26:56.450598',
 '2025-10-01 13:27:07.221574',
 '2025-10-01 13:27:18.645990',
 '2025-10-01 13:27:28.857369',
 '2025-10-01 13:27:39.441597',
 '2025-10-01 13:27:51.090463',
 '2025-10-01 13:28:01.936914',
 '2025-10-01 13:28:12.556691',
 '2025-10-01 13:28:24.925590',
 '2025-10-01 13:28:46.113821',
 '2025-10-01 13:28:56.389367',
 '2025-10-01 13:29:06.635144',
 '2025-10-01 13:29:16.797774',
 '2025-10-01 13:29:27.019385',
 '2025-10-01 13:29:37.208837',
 '2025-10-01 13:29:47.422263',
 '2025-10-01 13:29:57.642338',
 '2025-10-01 13:30:07.913922',
 '2025-10-01 13:30:18.923490',
 '2025-10-01 13:30:29.172936',
 '2025-10-01 13:30:39.346667',
 '2025-10-01 13:30:49.582096',
 '2025-10-01 13:30:59.762285',
 '2025-10-01 13:31:10.786717',
 '2025-10-01 13:31:21.016715',
 '2025-10-01 13:31:31.237463',
 '2025-10-01 13:31:41.461164',
 '2025-10-01 13:31:51.643532',
 '2025-10-01 13:32:01.901981',
 '2025-10-01 13:32:12.087438',
 '2025-10-01 13:32:22.279150',
 '2025-10-01 13:32:32.572196',
 '2025-10-01 13:32:42.822490',
 '2025-10-01 13:32:53.029157',
 '2025-10-01 13:33:03.211948',
 '2025-10-01 13:33:13.463893',
 '2025-10-01 13:33:23.701004',
 '2025-10-01 13:33:33.913546',
 '2025-10-01 13:33:44.113127',
 '2025-10-01 13:33:54.374315',
 '2025-10-01 13:34:04.610927',
 '2025-10-01 13:34:14.850592',
 '2025-10-01 13:34:26.045440',
 '2025-10-01 13:34:36.293358',
 '2025-10-01 13:34:47.571650',
 '2025-10-01 13:34:57.775492',
 '2025-10-01 13:35:07.933643',
 '2025-10-01 13:35:18.186738',
 '2025-10-01 13:35:28.366454',
 '2025-10-01 13:35:38.655016',
 '2025-10-01 13:35:48.893636',
 '2025-10-01 13:35:59.098769',
 '2025-10-01 13:36:09.882646',
 '2025-10-01 13:36:20.036468',
 '2025-10-01 13:36:30.269257',
 '2025-10-01 13:36:40.489256',
 '2025-10-01 13:36:50.718234',
 '2025-10-01 13:37:01.110668',
 '2025-10-01 13:37:11.411710',
 '2025-10-01 13:37:21.743296',
 '2025-10-01 13:37:32.121223',
 '2025-10-01 13:37:43.969770',
 '2025-10-01 13:37:55.211108',
 '2025-10-01 13:38:05.657038',
 '2025-10-01 13:38:15.945904',
 '2025-10-01 13:38:26.181725',
 '2025-10-01 13:38:36.360144',
 '2025-10-01 13:38:46.586393',
 '2025-10-01 13:38:56.780004',
 '2025-10-01 13:39:07.087226',
 '2025-10-01 13:39:17.347125',
 '2025-10-01 13:39:27.670443',
 '2025-10-01 13:39:37.867455',
 '2025-10-01 13:39:48.084486',
 '2025-10-01 13:39:59.267538',
 '2025-10-01 13:40:09.474729',
 '2025-10-01 13:40:20.656316',
 '2025-10-01 13:40:34.649766',
 '2025-10-01 13:40:45.254575',
 '2025-10-01 13:40:59.712065',
 '2025-10-01 13:41:10.082852',
 '2025-10-01 13:41:20.291895',
 '2025-10-01 13:41:30.490775',
 '2025-10-01 13:41:40.706153',
 '2025-10-01 13:41:51.067127',
 '2025-10-01 13:42:01.263140',
 '2025-10-01 13:42:11.553119',
 '2025-10-01 13:42:21.761381',
 '2025-10-01 13:42:31.931921',
 '2025-10-01 13:42:42.143594',
 '2025-10-01 13:42:52.371035',
 '2025-10-01 13:43:02.726999',
 '2025-10-01 13:43:13.880435',
 '2025-10-01 13:43:24.105627',
 '2025-10-01 13:43:34.339070',
 '2025-10-01 13:43:45.026551',
 '2025-10-01 13:43:56.400713',
 '2025-10-01 13:44:06.603920',
 '2025-10-01 13:44:16.836731',
 '2025-10-01 13:44:27.093049',
 '2025-10-01 13:44:38.151588',
 '2025-10-01 13:44:48.549378',
 '2025-10-01 13:44:59.719071',
 '2025-10-01 13:45:10.007752',
 '2025-10-01 13:45:20.264675',
 '2025-10-01 13:45:30.452701',
 '2025-10-01 13:45:40.618098',
 '2025-10-01 13:45:50.868576',
 '2025-10-01 13:46:01.108870',
 '2025-10-01 13:46:11.280885',
 '2025-10-01 13:46:21.475241',
 '2025-10-01 13:46:32.007263',
 '2025-10-01 13:46:42.367345',
 '2025-10-01 13:46:52.801649',
 '2025-10-01 13:47:02.989589',
 '2025-10-01 13:47:13.225556',
 '2025-10-01 13:47:23.415248',
 '2025-10-01 13:47:33.650674',
 '2025-10-01 13:47:43.851762',
 '2025-10-01 13:47:54.050275',
 '2025-10-01 13:48:04.289229',
 '2025-10-01 13:48:14.564471',
 '2025-10-01 13:48:24.735297',
 '2025-10-01 13:48:35.055762',
 '2025-10-01 13:48:45.342586',
 '2025-10-01 13:51:01.814084',
 '2025-10-01 13:51:12.052787',
 '2025-10-01 13:51:22.262342',
 '2025-10-01 13:51:32.453141',
 '2025-10-01 13:51:42.647759',
 '2025-10-01 13:51:52.890150',
 '2025-10-01 13:52:03.308548',
 '2025-10-01 13:52:13.520874',
 '2025-10-01 13:52:23.903267',
 '2025-10-01 13:52:34.125014',
 '2025-10-01 13:52:44.343105',
 '2025-10-01 13:52:54.637563',
 '2025-10-01 13:53:05.112972',
 '2025-10-01 13:53:16.986896',
 '2025-10-01 13:53:27.182285',
 '2025-10-01 13:53:37.379900',
 '2025-10-01 13:53:48.195805',
 '2025-10-01 13:53:58.406859',
 '2025-10-01 13:54:08.603267',
 '2025-10-01 13:54:18.796101',
 '2025-10-01 13:54:29.541571',
 '2025-10-01 13:54:39.792576',
 '2025-10-01 13:54:50.643344',
 '2025-10-01 13:55:00.829763',
 '2025-10-01 13:55:10.990000',
 '2025-10-01 13:55:21.241883',
 '2025-10-01 13:55:38.515021',
 '2025-10-01 13:55:48.750552',
 '2025-10-01 13:55:58.965872',
 '2025-10-01 13:56:09.203834',
 '2025-10-01 13:56:19.419992',
 '2025-10-01 13:56:29.623637',
 '2025-10-01 13:56:39.802846',
 '2025-10-01 13:56:50.681730',
 '2025-10-01 13:57:00.877404',
 '2025-10-01 13:57:11.062187',
 '2025-10-01 13:57:21.299217',
 '2025-10-01 13:57:31.511612',
 '2025-10-01 13:57:41.763079',
 '2025-10-01 13:57:51.972224',
 '2025-10-01 13:58:02.187034',
 '2025-10-01 13:58:12.380293',
 '2025-10-01 13:58:22.570603',
 '2025-10-01 13:58:32.771173',
 '2025-10-01 13:58:42.976881',
 '2025-10-01 13:58:53.158393',
 '2025-10-01 13:59:03.426331',
 '2025-10-01 13:59:13.927546',
 '2025-10-01 13:59:24.232125',
 '2025-10-01 13:59:34.497435',
 '2025-10-01 13:59:44.699293',
 '2025-10-01 13:59:54.936421',
 '2025-10-01 14:00:06.280565',
 '2025-10-01 14:00:16.466552',
 '2025-10-01 14:00:27.399529',
 '2025-10-01 14:00:37.651086',
 '2025-10-01 14:00:47.816086',
 '2025-10-01 14:00:58.111305',
 '2025-10-01 14:01:08.314185',
 '2025-10-01 14:01:19.425577',
 '2025-10-01 14:01:29.593373',
 '2025-10-01 14:01:39.800757',
 '2025-10-01 14:01:50.493054',
 '2025-10-01 14:02:00.757643',
 '2025-10-01 14:02:10.991224',
 '2025-10-01 14:02:21.247387',
 '2025-10-01 14:02:32.617962',
 '2025-10-01 14:02:42.768009',
 '2025-10-01 14:02:52.955200',
 '2025-10-01 14:03:03.297201',
 '2025-10-01 14:03:13.452838',
 '2025-10-01 14:03:23.624686',
 '2025-10-01 14:03:33.827172',
 '2025-10-01 14:03:43.990883',
 '2025-10-01 14:03:55.037054',
 '2025-10-01 14:04:05.342690',
 '2025-10-01 14:04:15.571586',
 '2025-10-01 14:04:26.836788',
 '2025-10-01 14:04:37.657032',
 '2025-10-01 14:04:48.032160',
 '2025-10-01 14:04:58.238890',
 '2025-10-01 14:05:09.328664',
 '2025-10-01 14:05:19.485723',
 '2025-10-01 14:05:29.757918',
 '2025-10-01 14:05:40.586546',
 '2025-10-01 14:05:50.782606',
 '2025-10-01 14:06:00.992161',
 '2025-10-01 14:06:11.319267',
 '2025-10-01 14:06:21.640689',
 '2025-10-01 14:06:31.920840',
 '2025-10-01 14:06:43.601337',
 '2025-10-01 14:06:53.842535',
 '2025-10-01 14:07:04.126174',
 '2025-10-01 14:07:14.470784',
 '2025-10-01 14:07:24.649428',
 '2025-10-01 14:07:34.848242',
 '2025-10-01 14:07:45.046466',
 '2025-10-01 14:07:55.223404',
 '2025-10-01 14:08:05.474700',
 '2025-10-01 14:08:15.629105',
 '2025-10-01 14:08:25.861715',
 '2025-10-01 14:08:36.019987',
 '2025-10-01 14:08:46.212422',
 '2025-10-01 14:08:56.486851',
 '2025-10-01 14:09:06.650957',
 '2025-10-01 14:09:16.802246',
 '2025-10-01 14:09:26.976667',
 '2025-10-01 14:09:37.264569',
 '2025-10-01 14:09:47.836836',
 '2025-10-01 14:09:58.134845',
 '2025-10-01 14:10:08.303100',
 '2025-10-01 14:10:18.481116',
 '2025-10-01 14:10:28.656297',
 '2025-10-01 14:10:38.855716',
 '2025-10-01 14:10:49.102556',
 '2025-10-01 14:10:59.477832',
 '2025-10-01 14:11:09.709172',
 '2025-10-01 14:11:19.919735',
 '2025-10-01 14:11:30.134047',
 '2025-10-01 14:11:40.373425',
 '2025-10-01 14:11:50.611844',
 '2025-10-01 14:12:00.892785',
 '2025-10-01 14:12:11.075561',
 '2025-10-01 14:12:21.327686',
 '2025-10-01 14:12:31.518128',
 '2025-10-01 14:12:41.717979',
 '2025-10-01 14:12:51.929024',
 '2025-10-01 14:13:02.161661',
 '2025-10-01 14:13:12.368222',
 '2025-10-01 14:13:23.377825',
 '2025-10-01 14:13:33.698010',
 '2025-10-01 14:13:43.849996',
 '2025-10-01 14:13:54.070803',
 '2025-10-01 14:14:04.270562',
 '2025-10-01 14:14:14.522067',
 '2025-10-01 14:14:24.670699',
 '2025-10-01 14:14:34.849387',
 '2025-10-01 14:14:45.086344',
 '2025-10-01 14:14:55.227791',
 '2025-10-01 14:15:05.510589',
 '2025-10-01 14:15:15.725528',
 '2025-10-01 14:15:25.992591',
 '2025-10-01 14:15:37.089128',
 '2025-10-01 14:15:47.323863',
 '2025-10-01 14:15:57.503631',
 '2025-10-01 14:16:07.675637',
 '2025-10-01 14:16:17.835197',
 '2025-10-01 14:16:28.007991',
 '2025-10-01 14:16:38.264094',
 '2025-10-01 14:16:48.450691',
 '2025-10-01 14:17:00.390513',
 '2025-10-01 14:17:10.556151',
 '2025-10-01 14:17:20.728340',
 '2025-10-01 14:17:30.873986',
 '2025-10-01 14:17:41.150175',
 '2025-10-01 14:17:52.221574',
 '2025-10-01 14:18:02.435009',
 '2025-10-01 14:18:12.742458',
 '2025-10-01 14:18:22.932925',
 '2025-10-01 14:18:33.114449',
 '2025-10-01 14:18:43.339145',
 '2025-10-01 14:18:53.546054',
 '2025-10-01 14:19:03.704265',
 '2025-10-01 14:19:13.978538',
 '2025-10-01 14:19:24.142380',
 '2025-10-01 14:19:34.425181',
 '2025-10-01 14:19:44.619160',
 '2025-10-01 14:19:54.927963',
 '2025-10-01 14:20:05.276011',
 '2025-10-01 14:20:15.493809',
 '2025-10-01 14:20:25.721048',
 '2025-10-01 14:20:35.902470',
 '2025-10-01 14:20:46.170036',
 '2025-10-01 14:20:56.625168',
 '2025-10-01 14:21:06.803158',
 '2025-10-01 14:21:16.969813',
 '2025-10-01 14:21:27.164136',
 '2025-10-01 14:21:37.450741',
 '2025-10-01 14:21:47.723252',
 '2025-10-01 14:21:57.928662',
 '2025-10-01 14:22:08.130831',
 '2025-10-01 14:22:18.336567',
 '2025-10-01 14:22:28.501906',
 '2025-10-01 14:22:38.691019',
 '2025-10-01 14:22:48.882797',
 '2025-10-01 14:22:59.063221',
 '2025-10-01 14:23:09.225160',
 '2025-10-01 14:23:19.398622',
 '2025-10-01 14:23:29.553474',
 '2025-10-01 14:23:39.765407',
 '2025-10-01 14:23:49.932264',
 '2025-10-01 14:24:00.076277',
 '2025-10-01 14:24:10.241738',
 '2025-10-01 14:24:20.408158',
 '2025-10-01 14:24:30.618334',
 '2025-10-01 14:24:40.793831',
 '2025-10-01 14:24:50.973557',
 '2025-10-01 14:25:01.134728',
 '2025-10-01 14:25:11.351235',
 '2025-10-01 14:25:21.581224',
 '2025-10-01 14:25:31.790154',
 '2025-10-01 14:25:41.960473',
 '2025-10-01 14:25:52.410942',
 '2025-10-01 14:26:02.640203',
 '2025-10-01 14:26:12.779853',
 '2025-10-01 14:26:22.939953',
 '2025-10-01 14:26:33.108222',
 '2025-10-01 14:26:43.319676',
 '2025-10-01 14:26:53.532287',
 '2025-10-01 14:27:03.694067',
 '2025-10-01 14:27:13.840422',
 '2025-10-01 14:27:24.051698',
 '2025-10-01 14:27:34.206853',
 '2025-10-01 14:27:44.375922',
 '2025-10-01 14:27:54.561063',
 '2025-10-01 14:28:04.787160',
 '2025-10-01 14:28:14.968666',
 '2025-10-01 14:28:25.141533',
 '2025-10-01 14:28:35.449611',
 '2025-10-01 14:28:45.642732',
 '2025-10-01 14:28:56.669609',
 '2025-10-01 14:29:06.862705',
 '2025-10-01 14:29:17.022230',
 '2025-10-01 14:29:27.169223',
 '2025-10-01 14:29:37.356759',
 '2025-10-01 14:29:47.528305',
 '2025-10-01 14:29:57.708093',
 '2025-10-01 14:30:07.896646',
 '2025-10-01 14:30:18.075801',
 '2025-10-01 14:30:28.219179',
 '2025-10-01 14:30:38.369753',
 '2025-10-01 14:30:48.546908',
 '2025-10-01 14:30:58.718607',
 '2025-10-01 14:31:09.004439',
 '2025-10-01 14:31:19.174669',
 '2025-10-01 14:31:29.394580',
 '2025-10-01 14:31:39.544309',
 '2025-10-01 14:31:49.703785',
 '2025-10-01 14:31:59.876067',
 '2025-10-01 14:32:10.051767',
 '2025-10-01 14:32:20.206936',
 '2025-10-01 14:32:30.693065',
 '2025-10-01 14:32:40.850323',
 '2025-10-01 14:32:51.097422',
 '2025-10-01 14:33:01.293988',
 '2025-10-01 14:33:11.528470',
 '2025-10-01 14:33:22.647299',
 '2025-10-01 14:33:32.786961',
 '2025-10-01 14:33:42.962837',
 '2025-10-01 14:33:53.114046',
 '2025-10-01 14:34:03.321427',
 '2025-10-01 14:34:13.518566',
 '2025-10-01 14:34:23.672468',
 '2025-10-01 14:34:33.836959',
 '2025-10-01 14:34:44.083674',
 '2025-10-01 14:34:54.255231',
 '2025-10-01 14:35:04.453716',
 '2025-10-01 14:35:14.702083',
 '2025-10-01 14:35:24.912298',
 '2025-10-01 14:35:35.169248',
 '2025-10-01 14:35:45.438651',
 '2025-10-01 14:35:55.615949',
 '2025-10-01 14:36:05.874679',
 '2025-10-01 14:36:16.037648',
 '2025-10-01 14:36:26.199891',
 '2025-10-01 14:36:36.346366',
 '2025-10-01 14:36:46.510594',
 '2025-10-01 14:36:57.510595',
 '2025-10-01 14:37:07.677262',
 '2025-10-01 14:37:17.851230',
 '2025-10-01 14:37:28.014948',
 '2025-10-01 14:37:38.251024',
 '2025-10-01 14:37:48.477189',
 '2025-10-01 14:37:58.684835',
 '2025-10-01 14:38:08.853674',
 '2025-10-01 14:38:19.026316',
 '2025-10-01 14:38:29.233392',
 '2025-10-01 14:38:39.413020',
 '2025-10-01 14:38:49.611891',
 '2025-10-01 14:38:59.790683',
 '2025-10-01 14:39:10.027357',
 '2025-10-01 14:39:20.175964',
 '2025-10-01 14:39:30.370704',
 '2025-10-01 14:39:40.553317',
 '2025-10-01 14:39:50.728831',
 '2025-10-01 14:40:01.012561',
 '2025-10-01 14:40:11.182454',
 '2025-10-01 14:40:21.360614',
 '2025-10-01 14:40:31.532582',
 '2025-10-01 14:40:41.684862',
 '2025-10-01 14:40:51.837225',
 '2025-10-01 14:41:01.970206',
 '2025-10-01 14:41:12.159170',
 '2025-10-01 14:41:22.370267',
 '2025-10-01 14:41:32.543454',
 '2025-10-01 14:41:42.751628',
 '2025-10-01 14:41:52.952640',
 '2025-10-01 14:42:03.137305',
 '2025-10-01 14:42:13.360463',
 '2025-10-01 14:42:23.600436',
 '2025-10-01 14:42:33.770300',
 '2025-10-01 14:42:43.978348',
 '2025-10-01 14:42:54.185132',
 '2025-10-01 14:43:04.348816',
 '2025-10-01 14:43:14.518202',
 '2025-10-01 14:43:24.710946',
 '2025-10-01 14:43:34.911910',
 '2025-10-01 14:43:45.077472',
 '2025-10-01 14:43:55.249360',

In [52]:
hours = [datetime_str.split(':')[0] for datetime_str in datetime_strs]
hours =sorted(set(hours))
hours

['2025-09-22 14',
 '2025-09-22 15',
 '2025-10-01 10',
 '2025-10-01 11',
 '2025-10-01 12',
 '2025-10-01 13',
 '2025-10-01 14',
 '2025-10-01 15',
 '2025-10-01 16',
 '2025-10-01 17',
 '2025-10-01 18',
 '2025-10-01 19',
 '2025-10-01 20',
 '2025-10-01 21',
 '2025-10-01 22',
 '2025-10-01 23',
 '2025-10-02 00',
 '2025-10-02 01',
 '2025-10-02 02',
 '2025-10-02 03',
 '2025-10-02 04',
 '2025-10-02 05',
 '2025-10-02 06',
 '2025-10-02 07',
 '2025-10-02 08',
 '2025-10-02 10',
 '2025-10-02 11',
 '2025-10-02 12',
 '2025-10-02 13',
 '2025-10-02 14',
 '2025-10-02 15',
 '2025-10-02 16']

In [53]:
hours[-1]

'2025-10-02 16'

In [54]:
from shining_pebbles import check_folder_and_create_folder

In [67]:
hours = [datetime_str.split(':')[0] for datetime_str in datetime_strs]
hours =sorted(set(hours))
hours

['2025-09-22 14',
 '2025-09-22 15',
 '2025-10-01 10',
 '2025-10-01 11',
 '2025-10-01 12',
 '2025-10-01 13',
 '2025-10-01 14',
 '2025-10-01 15',
 '2025-10-01 16',
 '2025-10-01 17',
 '2025-10-01 18',
 '2025-10-01 19',
 '2025-10-01 20',
 '2025-10-01 21',
 '2025-10-01 22',
 '2025-10-01 23',
 '2025-10-02 00',
 '2025-10-02 01',
 '2025-10-02 02',
 '2025-10-02 03',
 '2025-10-02 04',
 '2025-10-02 05',
 '2025-10-02 06',
 '2025-10-02 07',
 '2025-10-02 08',
 '2025-10-02 10',
 '2025-10-02 11',
 '2025-10-02 12',
 '2025-10-02 13',
 '2025-10-02 14',
 '2025-10-02 15',
 '2025-10-02 16']

In [68]:
def extract_datetime_str_from_filename(file_name:str)->str:
    return file_name.split('at')[-1].split('.csv')[0]

DATASET_BINANCE_PREFIX = 'dataset-binance_api-at'
file_names = scan_files_including_regex(file_folder=FILE_FOLDER['binance'], regex=DATASET_BINANCE_PREFIX)
datetime_strs = [extract_datetime_str_from_filename(file_name) for file_name in file_names]
datetime_strs

hours = [datetime_str.split(':')[0] for datetime_str in datetime_strs]
hours =sorted(set(hours))
hours

['2025-10-02 17', '2025-10-02 18', '2025-10-02 19']

In [60]:
file_folder = os.path.join(FILE_FOLDER['binance'], hours[0])
check_folder_and_create_folder(file_folder)

Created: data/dataset-binance/2025-09-22 14

'data/dataset-binance/2025-09-22 14'

In [62]:
file_names = scan_files_including_regex(file_folder=FILE_FOLDER['binance'], regex=f'{hours[0]}.*.csv')
file_names

['dataset-binance_api-at2025-09-22 14:12:15.558889.csv',
 'dataset-binance_api-at2025-09-22 14:36:51.024951.csv']

In [69]:
for hour in hours:
    file_folder = os.path.join(FILE_FOLDER['binance'], hour)
    check_folder_and_create_folder(file_folder)
    file_names = scan_files_including_regex(file_folder=FILE_FOLDER['binance'], regex=f'{hour}.*.csv')
    for file_name in file_names:
        move_files(regex=file_name, folder_from=FILE_FOLDER['binance'], folder_to=file_folder, option='move')

Created: data/dataset-binance/2025-10-02 17
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:00:02.187796.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:00:02.187796.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:00:12.317182.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:00:12.317182.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:00:22.448697.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:00:22.448697.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:00:32.685136.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:00:32.685136.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:00:42.848936.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:00:42.848936.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:00:53.067977.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:00:53.067977.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:01:03.215867.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:01:03.215867.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:01:13.355895.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:01:13.355895.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:01:23.484538.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:01:23.484538.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:01:33.656727.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:01:33.656727.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:01:43.795106.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:01:43.795106.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:01:53.940314.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:01:53.940314.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:02:04.074908.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:02:04.074908.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:02:14.208646.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:02:14.208646.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:02:24.352225.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:02:24.352225.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:02:34.504117.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:02:34.504117.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:02:44.644335.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:02:44.644335.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:02:54.821633.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:02:54.821633.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:03:04.965278.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:03:04.965278.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:03:15.101789.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:03:15.101789.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:03:25.255056.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:03:25.255056.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:03:35.400431.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:03:35.400431.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:03:45.541885.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:03:45.541885.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:22:15.131608.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:22:15.131608.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:22:25.572680.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:22:25.572680.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:23:51.032377.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:23:51.032377.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:40:52.533530.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:40:52.533530.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:41:02.940989.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:41:02.940989.csv]
Already exists: data/dataset-binance/2025-10-02 17
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 17:41:13.167904.csv] -> [data/dataset-binance/2025-10-02 17/dataset-binance_api-at2025-10-02 17:41:13.167904.csv]
Created: data/dataset-binance/2025-10-02 18
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:10:20.097365.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:10:20.097365.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:10:30.658325.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:10:30.658325.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:10:41.255903.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:10:41.255903.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:28:05.598168.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:28:05.598168.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:52:45.324394.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:52:45.324394.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:52:55.520961.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:52:55.520961.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:53:05.700264.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:53:05.700264.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:53:15.859374.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:53:15.859374.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:53:26.074776.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:53:26.074776.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:53:36.275302.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:53:36.275302.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:53:46.664902.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:53:46.664902.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:53:57.119541.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:53:57.119541.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:54:07.262043.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:54:07.262043.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:54:17.420858.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:54:17.420858.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:54:27.584115.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:54:27.584115.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:54:37.868454.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:54:37.868454.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:54:48.266846.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:54:48.266846.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:54:58.403748.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:54:58.403748.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:55:08.602653.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:55:08.602653.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:55:18.749651.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:55:18.749651.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:55:28.957241.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:55:28.957241.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:55:39.348136.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:55:39.348136.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:55:49.475226.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:55:49.475226.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:55:59.817799.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:55:59.817799.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:56:09.983634.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:56:09.983634.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:56:20.195719.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:56:20.195719.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:56:30.526328.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:56:30.526328.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:56:40.707011.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:56:40.707011.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:56:50.890543.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:56:50.890543.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:57:01.246349.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:57:01.246349.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:57:11.403238.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:57:11.403238.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:57:21.588966.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:57:21.588966.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:57:31.782117.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:57:31.782117.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:57:42.016532.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:57:42.016532.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:57:52.153894.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:57:52.153894.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:58:02.286441.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:58:02.286441.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:58:12.422194.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:58:12.422194.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:58:22.586616.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:58:22.586616.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:58:32.720287.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:58:32.720287.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:58:42.893514.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:58:42.893514.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:58:53.018415.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:58:53.018415.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:59:03.174301.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:59:03.174301.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:59:13.338792.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:59:13.338792.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:59:23.477943.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:59:23.477943.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:59:33.604895.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:59:33.604895.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:59:43.792851.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:59:43.792851.csv]
Already exists: data/dataset-binance/2025-10-02 18
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 18:59:53.927700.csv] -> [data/dataset-binance/2025-10-02 18/dataset-binance_api-at2025-10-02 18:59:53.927700.csv]
Created: data/dataset-binance/2025-10-02 19
Already exists: data/dataset-binance/2025-10-02 19
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 19:00:04.048847.csv] -> [data/dataset-binance/2025-10-02 19/dataset-binance_api-at2025-10-02 19:00:04.048847.csv]
Already exists: data/dataset-binance/2025-10-02 19
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 19:00:14.389266.csv] -> [data/dataset-binance/2025-10-02 19/dataset-binance_api-at2025-10-02 19:00:14.389266.csv]
Already exists: data/dataset-binance/2025-10-02 19
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 19:00:24.577212.csv] -> [data/dataset-binance/2025-10-02 19/dataset-binance_api-at2025-10-02 19:00:24.577212.csv]
Already exists: data/dataset-binance/2025-10-02 19
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 19:00:34.718397.csv] -> [data/dataset-binance/2025-10-02 19/dataset-binance_api-at2025-10-02 19:00:34.718397.csv]
Already exists: data/dataset-binance/2025-10-02 19
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 19:00:44.917258.csv] -> [data/dataset-binance/2025-10-02 19/dataset-binance_api-at2025-10-02 19:00:44.917258.csv]
Already exists: data/dataset-binance/2025-10-02 19
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 19:00:55.046429.csv] -> [data/dataset-binance/2025-10-02 19/dataset-binance_api-at2025-10-02 19:00:55.046429.csv]
Already exists: data/dataset-binance/2025-10-02 19
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 19:01:05.177336.csv] -> [data/dataset-binance/2025-10-02 19/dataset-binance_api-at2025-10-02 19:01:05.177336.csv]
Already exists: data/dataset-binance/2025-10-02 19
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 19:01:15.515508.csv] -> [data/dataset-binance/2025-10-02 19/dataset-binance_api-at2025-10-02 19:01:15.515508.csv]
Already exists: data/dataset-binance/2025-10-02 19
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 19:01:25.676464.csv] -> [data/dataset-binance/2025-10-02 19/dataset-binance_api-at2025-10-02 19:01:25.676464.csv]
Already exists: data/dataset-binance/2025-10-02 19
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 19:01:35.811883.csv] -> [data/dataset-binance/2025-10-02 19/dataset-binance_api-at2025-10-02 19:01:35.811883.csv]
Already exists: data/dataset-binance/2025-10-02 19
Moved: [data/dataset-binance/dataset-binance_api-at2025-10-02 19:01:46.086444.csv] -> [data/dataset-binance/2025-10-02 19/dataset-binance_api-at2025-10-02 19:01:46.086444.csv]
Already exists: data/dataset-binance/2025-10-02 19

In [ ]:
file_names = scan_files_including_regex(file_folder=FILE_FOLDER['binance'], regex=)

In [5]:
FILE_FOLDER

{'binance': 'data/dataset-binance', 'total': 'data/dataset-total'}

In [ ]:
DATASET_BINANCE_PREFIX = 'dataset-binance_api-at'
file_names = scan_files_including_regex(file_folder=FILE_FOLDER['binance'], regex=DATASET_BINANCE_PREFIX)
file_names

In [45]:
DATASET_BINANCE_PREFIX = 'dataset-binance_api-at'
file_names = scan_files_including_regex(file_folder=FILE_FOLDER['binance'], regex=DATASET_BINANCE_PREFIX)
file_names

['dataset-binance_api-at2025-09-22 14:12:15.558889.csv',
 'dataset-binance_api-at2025-09-22 14:36:51.024951.csv',
 'dataset-binance_api-at2025-09-22 15:13:32.437206.csv',
 'dataset-binance_api-at2025-09-22 15:13:42.324450.csv',
 'dataset-binance_api-at2025-09-22 15:13:44.929049.csv',
 'dataset-binance_api-at2025-09-22 15:13:57.197217.csv',
 'dataset-binance_api-at2025-09-22 15:14:04.108237.csv',
 'dataset-binance_api-at2025-10-01 10:45:39.493475.csv',
 'dataset-binance_api-at2025-10-01 10:45:43.572308.csv',
 'dataset-binance_api-at2025-10-01 10:45:45.038490.csv',
 'dataset-binance_api-at2025-10-01 10:45:45.870827.csv',
 'dataset-binance_api-at2025-10-01 10:45:47.456667.csv',
 'dataset-binance_api-at2025-10-01 10:45:49.275929.csv',
 'dataset-binance_api-at2025-10-01 10:45:50.254635.csv',
 'dataset-binance_api-at2025-10-01 10:45:51.168384.csv',
 'dataset-binance_api-at2025-10-01 10:45:52.072152.csv',
 'dataset-binance_api-at2025-10-01 10:45:52.998195.csv',
 'dataset-binance_api-at2025-10-01 10:45:53.817472.csv',
 'dataset-binance_api-at2025-10-01 10:45:54.834691.csv',
 'dataset-binance_api-at2025-10-01 10:45:55.687214.csv',
 'dataset-binance_api-at2025-10-01 10:53:32.732888.csv',
 'dataset-binance_api-at2025-10-01 11:05:53.034961.csv',
 'dataset-binance_api-at2025-10-01 11:06:03.214001.csv',
 'dataset-binance_api-at2025-10-01 11:06:13.409766.csv',
 'dataset-binance_api-at2025-10-01 11:06:23.615444.csv',
 'dataset-binance_api-at2025-10-01 11:06:33.816770.csv',
 'dataset-binance_api-at2025-10-01 11:06:43.976897.csv',
 'dataset-binance_api-at2025-10-01 11:06:54.164687.csv',
 'dataset-binance_api-at2025-10-01 11:07:04.324132.csv',
 'dataset-binance_api-at2025-10-01 11:07:14.526111.csv',
 'dataset-binance_api-at2025-10-01 11:07:24.709910.csv',
 'dataset-binance_api-at2025-10-01 11:07:34.936393.csv',
 'dataset-binance_api-at2025-10-01 11:07:45.100529.csv',
 'dataset-binance_api-at2025-10-01 11:07:55.360115.csv',
 'dataset-binance_api-at2025-10-01 11:08:05.536255.csv',
 'dataset-binance_api-at2025-10-01 11:08:15.699199.csv',
 'dataset-binance_api-at2025-10-01 11:08:25.890581.csv',
 'dataset-binance_api-at2025-10-01 11:08:36.065507.csv',
 'dataset-binance_api-at2025-10-01 11:08:46.212176.csv',
 'dataset-binance_api-at2025-10-01 11:08:56.360178.csv',
 'dataset-binance_api-at2025-10-01 11:09:06.545494.csv',
 'dataset-binance_api-at2025-10-01 11:09:16.732794.csv',
 'dataset-binance_api-at2025-10-01 11:09:26.874669.csv',
 'dataset-binance_api-at2025-10-01 11:09:37.042067.csv',
 'dataset-binance_api-at2025-10-01 11:09:47.210575.csv',
 'dataset-binance_api-at2025-10-01 11:09:57.382201.csv',
 'dataset-binance_api-at2025-10-01 11:10:07.535110.csv',
 'dataset-binance_api-at2025-10-01 11:10:17.690720.csv',
 'dataset-binance_api-at2025-10-01 11:10:27.850876.csv',
 'dataset-binance_api-at2025-10-01 11:10:38.097263.csv',
 'dataset-binance_api-at2025-10-01 11:10:48.275960.csv',
 'dataset-binance_api-at2025-10-01 11:10:58.474196.csv',
 'dataset-binance_api-at2025-10-01 11:11:08.609383.csv',
 'dataset-binance_api-at2025-10-01 11:11:18.755025.csv',
 'dataset-binance_api-at2025-10-01 11:11:28.888563.csv',
 'dataset-binance_api-at2025-10-01 11:11:39.056709.csv',
 'dataset-binance_api-at2025-10-01 11:11:49.191821.csv',
 'dataset-binance_api-at2025-10-01 11:14:00.669660.csv',
 'dataset-binance_api-at2025-10-01 11:14:11.330199.csv',
 'dataset-binance_api-at2025-10-01 12:37:09.941490.csv',
 'dataset-binance_api-at2025-10-01 12:37:20.414823.csv',
 'dataset-binance_api-at2025-10-01 12:49:09.240350.csv',
 'dataset-binance_api-at2025-10-01 12:49:19.558931.csv',
 'dataset-binance_api-at2025-10-01 12:49:29.768361.csv',
 'dataset-binance_api-at2025-10-01 12:49:39.943969.csv',
 'dataset-binance_api-at2025-10-01 12:56:40.983929.csv',
 'dataset-binance_api-at2025-10-01 12:56:51.322061.csv',
 'dataset-binance_api-at2025-10-01 12:57:01.679620.csv',
 'dataset-binance_api-at2025-10-01 12:57:11.875653.csv',
 'dataset-binance_api-at2025-10-01 12:58:04.037209.csv',
 'dataset-binance_api-at2025-10-01 12:58:14.405660.csv',
 'dataset-binance_api-at2025-10-01 12:58:24.622651.csv',
 'dataset-binance_api-at2025-10-01 12:58:34.853284.csv',
 'dataset-binance_api-at2025-10-01 12:58:46.390962.csv',
 'dataset-binance_api-at2025-10-01 12:58:56.586105.csv',
 'dataset-binance_api-at2025-10-01 12:59:06.757927.csv',
 'dataset-binance_api-at2025-10-01 12:59:16.924617.csv',
 'dataset-binance_api-at2025-10-01 13:01:00.718376.csv',
 'dataset-binance_api-at2025-10-01 13:01:11.232469.csv',
 'dataset-binance_api-at2025-10-01 13:01:42.075645.csv',
 'dataset-binance_api-at2025-10-01 13:01:52.443548.csv',
 'dataset-binance_api-at2025-10-01 13:02:02.931495.csv',
 'dataset-binance_api-at2025-10-01 13:02:13.111562.csv',
 'dataset-binance_api-at2025-10-01 13:03:10.701921.csv',
 'dataset-binance_api-at2025-10-01 13:03:21.083706.csv',
 'dataset-binance_api-at2025-10-01 13:03:31.544246.csv',
 'dataset-binance_api-at2025-10-01 13:03:42.660240.csv',
 'dataset-binance_api-at2025-10-01 13:03:53.399241.csv',
 'dataset-binance_api-at2025-10-01 13:04:04.793570.csv',
 'dataset-binance_api-at2025-10-01 13:04:15.057347.csv',
 'dataset-binance_api-at2025-10-01 13:04:25.279739.csv',
 'dataset-binance_api-at2025-10-01 13:04:38.869161.csv',
 'dataset-binance_api-at2025-10-01 13:04:49.501548.csv',
 'dataset-binance_api-at2025-10-01 13:04:59.957084.csv',
 'dataset-binance_api-at2025-10-01 13:05:10.399347.csv',
 'dataset-binance_api-at2025-10-01 13:05:21.996818.csv',
 'dataset-binance_api-at2025-10-01 13:05:32.198062.csv',
 'dataset-binance_api-at2025-10-01 13:05:42.751156.csv',
 'dataset-binance_api-at2025-10-01 13:05:53.092701.csv',
 'dataset-binance_api-at2025-10-01 13:06:03.879166.csv',
 'dataset-binance_api-at2025-10-01 13:06:14.711475.csv',
 'dataset-binance_api-at2025-10-01 13:06:24.964406.csv',
 'dataset-binance_api-at2025-10-01 13:06:37.947457.csv',
 'dataset-binance_api-at2025-10-01 13:06:48.888449.csv',
 'dataset-binance_api-at2025-10-01 13:07:00.697791.csv',
 'dataset-binance_api-at2025-10-01 13:07:11.733244.csv',
 'dataset-binance_api-at2025-10-01 13:07:21.994082.csv',
 'dataset-binance_api-at2025-10-01 13:07:32.742785.csv',
 'dataset-binance_api-at2025-10-01 13:07:42.993502.csv',
 'dataset-binance_api-at2025-10-01 13:07:53.375453.csv',
 'dataset-binance_api-at2025-10-01 13:08:05.647416.csv',
 'dataset-binance_api-at2025-10-01 13:08:16.001365.csv',
 'dataset-binance_api-at2025-10-01 13:08:50.876704.csv',
 'dataset-binance_api-at2025-10-01 13:09:02.637033.csv',
 'dataset-binance_api-at2025-10-01 13:09:13.391309.csv',
 'dataset-binance_api-at2025-10-01 13:09:24.675636.csv',
 'dataset-binance_api-at2025-10-01 13:09:35.939977.csv',
 'dataset-binance_api-at2025-10-01 13:09:47.658174.csv',
 'dataset-binance_api-at2025-10-01 13:09:58.898394.csv',
 'dataset-binance_api-at2025-10-01 13:10:09.483793.csv',
 'dataset-binance_api-at2025-10-01 13:10:24.809651.csv',
 'dataset-binance_api-at2025-10-01 13:10:35.137401.csv',
 'dataset-binance_api-at2025-10-01 13:10:45.930968.csv',
 'dataset-binance_api-at2025-10-01 13:10:56.413773.csv',
 'dataset-binance_api-at2025-10-01 13:11:06.673597.csv',
 'dataset-binance_api-at2025-10-01 13:11:19.665754.csv',
 'dataset-binance_api-at2025-10-01 13:11:29.928015.csv',
 'dataset-binance_api-at2025-10-01 13:11:40.473656.csv',
 'dataset-binance_api-at2025-10-01 13:11:50.608421.csv',
 'dataset-binance_api-at2025-10-01 13:12:02.235946.csv',
 'dataset-binance_api-at2025-10-01 13:12:12.508934.csv',
 'dataset-binance_api-at2025-10-01 13:12:23.028914.csv',
 'dataset-binance_api-at2025-10-01 13:12:34.221298.csv',
 'dataset-binance_api-at2025-10-01 13:12:44.741413.csv',
 'dataset-binance_api-at2025-10-01 13:12:56.744041.csv',
 'dataset-binance_api-at2025-10-01 13:13:09.419102.csv',
 'dataset-binance_api-at2025-10-01 13:13:20.121904.csv',
 'dataset-binance_api-at2025-10-01 13:13:31.331059.csv',
 'dataset-binance_api-at2025-10-01 13:13:41.697555.csv',
 'dataset-binance_api-at2025-10-01 13:13:52.448531.csv',
 'dataset-binance_api-at2025-10-01 13:14:02.975175.csv',
 'dataset-binance_api-at2025-10-01 13:14:14.764309.csv',
 'dataset-binance_api-at2025-10-01 13:14:25.006507.csv',
 'dataset-binance_api-at2025-10-01 13:14:38.917103.csv',
 'dataset-binance_api-at2025-10-01 13:14:56.407622.csv',
 'dataset-binance_api-at2025-10-01 13:15:06.717935.csv',
 'dataset-binance_api-at2025-10-01 13:15:16.955800.csv',
 'dataset-binance_api-at2025-10-01 13:15:27.247958.csv',
 'dataset-binance_api-at2025-10-01 13:15:40.355286.csv',
 'dataset-binance_api-at2025-10-01 13:15:50.596524.csv',
 'dataset-binance_api-at2025-10-01 13:16:01.026622.csv',
 'dataset-binance_api-at2025-10-01 13:16:12.339518.csv',
 'dataset-binance_api-at2025-10-01 13:16:22.584045.csv',
 'dataset-binance_api-at2025-10-01 13:16:32.821317.csv',
 'dataset-binance_api-at2025-10-01 13:16:45.769997.csv',
 'dataset-binance_api-at2025-10-01 13:16:57.964636.csv',
 'dataset-binance_api-at2025-10-01 13:17:09.329148.csv',
 'dataset-binance_api-at2025-10-01 13:17:20.610012.csv',
 'dataset-binance_api-at2025-10-01 13:17:32.050028.csv',
 'dataset-binance_api-at2025-10-01 13:17:43.410994.csv',
 'dataset-binance_api-at2025-10-01 13:17:53.675885.csv',
 'dataset-binance_api-at2025-10-01 13:18:04.348068.csv',
 'dataset-binance_api-at2025-10-01 13:18:14.659651.csv',
 'dataset-binance_api-at2025-10-01 13:18:24.900409.csv',
 'dataset-binance_api-at2025-10-01 13:18:35.794689.csv',
 'dataset-binance_api-at2025-10-01 13:18:46.211239.csv',
 'dataset-binance_api-at2025-10-01 13:18:56.425553.csv',
 'dataset-binance_api-at2025-10-01 13:19:06.783184.csv',
 'dataset-binance_api-at2025-10-01 13:19:17.085056.csv',
 'dataset-binance_api-at2025-10-01 13:19:27.331126.csv',
 'dataset-binance_api-at2025-10-01 13:19:37.700378.csv',
 'dataset-binance_api-at2025-10-01 13:19:48.351050.csv',
 'dataset-binance_api-at2025-10-01 13:19:58.557340.csv',
 'dataset-binance_api-at2025-10-01 13:20:09.029776.csv',
 'dataset-binance_api-at2025-10-01 13:20:19.241419.csv',
 'dataset-binance_api-at2025-10-01 13:20:29.517433.csv',
 'dataset-binance_api-at2025-10-01 13:20:39.704556.csv',
 'dataset-binance_api-at2025-10-01 13:20:50.948142.csv',
 'dataset-binance_api-at2025-10-01 13:21:01.313176.csv',
 'dataset-binance_api-at2025-10-01 13:21:11.613412.csv',
 'dataset-binance_api-at2025-10-01 13:21:21.855786.csv',
 'dataset-binance_api-at2025-10-01 13:21:33.083827.csv',
 'dataset-binance_api-at2025-10-01 13:21:44.912438.csv',
 'dataset-binance_api-at2025-10-01 13:21:55.142309.csv',
 'dataset-binance_api-at2025-10-01 13:22:05.450054.csv',
 'dataset-binance_api-at2025-10-01 13:22:15.705951.csv',
 'dataset-binance_api-at2025-10-01 13:22:26.290765.csv',
 'dataset-binance_api-at2025-10-01 13:22:38.163255.csv',
 'dataset-binance_api-at2025-10-01 13:22:48.687247.csv',
 'dataset-binance_api-at2025-10-01 13:22:59.031961.csv',
 'dataset-binance_api-at2025-10-01 13:23:09.681310.csv',
 'dataset-binance_api-at2025-10-01 13:23:20.962303.csv',
 'dataset-binance_api-at2025-10-01 13:23:32.003246.csv',
 'dataset-binance_api-at2025-10-01 13:23:42.263401.csv',
 'dataset-binance_api-at2025-10-01 13:23:54.560381.csv',
 'dataset-binance_api-at2025-10-01 13:24:05.002567.csv',
 'dataset-binance_api-at2025-10-01 13:24:15.170624.csv',
 'dataset-binance_api-at2025-10-01 13:24:25.922627.csv',
 'dataset-binance_api-at2025-10-01 13:24:36.165524.csv',
 'dataset-binance_api-at2025-10-01 13:24:46.371683.csv',
 'dataset-binance_api-at2025-10-01 13:24:56.617571.csv',
 'dataset-binance_api-at2025-10-01 13:25:08.406880.csv',
 'dataset-binance_api-at2025-10-01 13:25:19.146565.csv',
 'dataset-binance_api-at2025-10-01 13:25:29.881586.csv',
 'dataset-binance_api-at2025-10-01 13:25:41.210395.csv',
 'dataset-binance_api-at2025-10-01 13:25:51.489172.csv',
 'dataset-binance_api-at2025-10-01 13:26:01.764209.csv',
 'dataset-binance_api-at2025-10-01 13:26:12.298378.csv',
 'dataset-binance_api-at2025-10-01 13:26:23.818827.csv',
 'dataset-binance_api-at2025-10-01 13:26:34.120249.csv',
 'dataset-binance_api-at2025-10-01 13:26:46.147817.csv',
 'dataset-binance_api-at2025-10-01 13:26:56.450598.csv',
 'dataset-binance_api-at2025-10-01 13:27:07.221574.csv',
 'dataset-binance_api-at2025-10-01 13:27:18.645990.csv',
 'dataset-binance_api-at2025-10-01 13:27:28.857369.csv',
 'dataset-binance_api-at2025-10-01 13:27:39.441597.csv',
 'dataset-binance_api-at2025-10-01 13:27:51.090463.csv',
 'dataset-binance_api-at2025-10-01 13:28:01.936914.csv',
 'dataset-binance_api-at2025-10-01 13:28:12.556691.csv',
 'dataset-binance_api-at2025-10-01 13:28:24.925590.csv',
 'dataset-binance_api-at2025-10-01 13:28:46.113821.csv',
 'dataset-binance_api-at2025-10-01 13:28:56.389367.csv',
 'dataset-binance_api-at2025-10-01 13:29:06.635144.csv',
 'dataset-binance_api-at2025-10-01 13:29:16.797774.csv',
 'dataset-binance_api-at2025-10-01 13:29:27.019385.csv',
 'dataset-binance_api-at2025-10-01 13:29:37.208837.csv',
 'dataset-binance_api-at2025-10-01 13:29:47.422263.csv',
 'dataset-binance_api-at2025-10-01 13:29:57.642338.csv',
 'dataset-binance_api-at2025-10-01 13:30:07.913922.csv',
 'dataset-binance_api-at2025-10-01 13:30:18.923490.csv',
 'dataset-binance_api-at2025-10-01 13:30:29.172936.csv',
 'dataset-binance_api-at2025-10-01 13:30:39.346667.csv',
 'dataset-binance_api-at2025-10-01 13:30:49.582096.csv',
 'dataset-binance_api-at2025-10-01 13:30:59.762285.csv',
 'dataset-binance_api-at2025-10-01 13:31:10.786717.csv',
 'dataset-binance_api-at2025-10-01 13:31:21.016715.csv',
 'dataset-binance_api-at2025-10-01 13:31:31.237463.csv',
 'dataset-binance_api-at2025-10-01 13:31:41.461164.csv',
 'dataset-binance_api-at2025-10-01 13:31:51.643532.csv',
 'dataset-binance_api-at2025-10-01 13:32:01.901981.csv',
 'dataset-binance_api-at2025-10-01 13:32:12.087438.csv',
 'dataset-binance_api-at2025-10-01 13:32:22.279150.csv',
 'dataset-binance_api-at2025-10-01 13:32:32.572196.csv',
 'dataset-binance_api-at2025-10-01 13:32:42.822490.csv',
 'dataset-binance_api-at2025-10-01 13:32:53.029157.csv',
 'dataset-binance_api-at2025-10-01 13:33:03.211948.csv',
 'dataset-binance_api-at2025-10-01 13:33:13.463893.csv',
 'dataset-binance_api-at2025-10-01 13:33:23.701004.csv',
 'dataset-binance_api-at2025-10-01 13:33:33.913546.csv',
 'dataset-binance_api-at2025-10-01 13:33:44.113127.csv',
 'dataset-binance_api-at2025-10-01 13:33:54.374315.csv',
 'dataset-binance_api-at2025-10-01 13:34:04.610927.csv',
 'dataset-binance_api-at2025-10-01 13:34:14.850592.csv',
 'dataset-binance_api-at2025-10-01 13:34:26.045440.csv',
 'dataset-binance_api-at2025-10-01 13:34:36.293358.csv',
 'dataset-binance_api-at2025-10-01 13:34:47.571650.csv',
 'dataset-binance_api-at2025-10-01 13:34:57.775492.csv',
 'dataset-binance_api-at2025-10-01 13:35:07.933643.csv',
 'dataset-binance_api-at2025-10-01 13:35:18.186738.csv',
 'dataset-binance_api-at2025-10-01 13:35:28.366454.csv',
 'dataset-binance_api-at2025-10-01 13:35:38.655016.csv',
 'dataset-binance_api-at2025-10-01 13:35:48.893636.csv',
 'dataset-binance_api-at2025-10-01 13:35:59.098769.csv',
 'dataset-binance_api-at2025-10-01 13:36:09.882646.csv',
 'dataset-binance_api-at2025-10-01 13:36:20.036468.csv',
 'dataset-binance_api-at2025-10-01 13:36:30.269257.csv',
 'dataset-binance_api-at2025-10-01 13:36:40.489256.csv',
 'dataset-binance_api-at2025-10-01 13:36:50.718234.csv',
 'dataset-binance_api-at2025-10-01 13:37:01.110668.csv',
 'dataset-binance_api-at2025-10-01 13:37:11.411710.csv',
 'dataset-binance_api-at2025-10-01 13:37:21.743296.csv',
 'dataset-binance_api-at2025-10-01 13:37:32.121223.csv',
 'dataset-binance_api-at2025-10-01 13:37:43.969770.csv',
 'dataset-binance_api-at2025-10-01 13:37:55.211108.csv',
 'dataset-binance_api-at2025-10-01 13:38:05.657038.csv',
 'dataset-binance_api-at2025-10-01 13:38:15.945904.csv',
 'dataset-binance_api-at2025-10-01 13:38:26.181725.csv',
 'dataset-binance_api-at2025-10-01 13:38:36.360144.csv',
 'dataset-binance_api-at2025-10-01 13:38:46.586393.csv',
 'dataset-binance_api-at2025-10-01 13:38:56.780004.csv',
 'dataset-binance_api-at2025-10-01 13:39:07.087226.csv',
 'dataset-binance_api-at2025-10-01 13:39:17.347125.csv',
 'dataset-binance_api-at2025-10-01 13:39:27.670443.csv',
 'dataset-binance_api-at2025-10-01 13:39:37.867455.csv',
 'dataset-binance_api-at2025-10-01 13:39:48.084486.csv',
 'dataset-binance_api-at2025-10-01 13:39:59.267538.csv',
 'dataset-binance_api-at2025-10-01 13:40:09.474729.csv',
 'dataset-binance_api-at2025-10-01 13:40:20.656316.csv',
 'dataset-binance_api-at2025-10-01 13:40:34.649766.csv',
 'dataset-binance_api-at2025-10-01 13:40:45.254575.csv',
 'dataset-binance_api-at2025-10-01 13:40:59.712065.csv',
 'dataset-binance_api-at2025-10-01 13:41:10.082852.csv',
 'dataset-binance_api-at2025-10-01 13:41:20.291895.csv',
 'dataset-binance_api-at2025-10-01 13:41:30.490775.csv',
 'dataset-binance_api-at2025-10-01 13:41:40.706153.csv',
 'dataset-binance_api-at2025-10-01 13:41:51.067127.csv',
 'dataset-binance_api-at2025-10-01 13:42:01.263140.csv',
 'dataset-binance_api-at2025-10-01 13:42:11.553119.csv',
 'dataset-binance_api-at2025-10-01 13:42:21.761381.csv',
 'dataset-binance_api-at2025-10-01 13:42:31.931921.csv',
 'dataset-binance_api-at2025-10-01 13:42:42.143594.csv',
 'dataset-binance_api-at2025-10-01 13:42:52.371035.csv',
 'dataset-binance_api-at2025-10-01 13:43:02.726999.csv',
 'dataset-binance_api-at2025-10-01 13:43:13.880435.csv',
 'dataset-binance_api-at2025-10-01 13:43:24.105627.csv',
 'dataset-binance_api-at2025-10-01 13:43:34.339070.csv',
 'dataset-binance_api-at2025-10-01 13:43:45.026551.csv',
 'dataset-binance_api-at2025-10-01 13:43:56.400713.csv',
 'dataset-binance_api-at2025-10-01 13:44:06.603920.csv',
 'dataset-binance_api-at2025-10-01 13:44:16.836731.csv',
 'dataset-binance_api-at2025-10-01 13:44:27.093049.csv',
 'dataset-binance_api-at2025-10-01 13:44:38.151588.csv',
 'dataset-binance_api-at2025-10-01 13:44:48.549378.csv',
 'dataset-binance_api-at2025-10-01 13:44:59.719071.csv',
 'dataset-binance_api-at2025-10-01 13:45:10.007752.csv',
 'dataset-binance_api-at2025-10-01 13:45:20.264675.csv',
 'dataset-binance_api-at2025-10-01 13:45:30.452701.csv',
 'dataset-binance_api-at2025-10-01 13:45:40.618098.csv',
 'dataset-binance_api-at2025-10-01 13:45:50.868576.csv',
 'dataset-binance_api-at2025-10-01 13:46:01.108870.csv',
 'dataset-binance_api-at2025-10-01 13:46:11.280885.csv',
 'dataset-binance_api-at2025-10-01 13:46:21.475241.csv',
 'dataset-binance_api-at2025-10-01 13:46:32.007263.csv',
 'dataset-binance_api-at2025-10-01 13:46:42.367345.csv',
 'dataset-binance_api-at2025-10-01 13:46:52.801649.csv',
 'dataset-binance_api-at2025-10-01 13:47:02.989589.csv',
 'dataset-binance_api-at2025-10-01 13:47:13.225556.csv',
 'dataset-binance_api-at2025-10-01 13:47:23.415248.csv',
 'dataset-binance_api-at2025-10-01 13:47:33.650674.csv',
 'dataset-binance_api-at2025-10-01 13:47:43.851762.csv',
 'dataset-binance_api-at2025-10-01 13:47:54.050275.csv',
 'dataset-binance_api-at2025-10-01 13:48:04.289229.csv',
 'dataset-binance_api-at2025-10-01 13:48:14.564471.csv',
 'dataset-binance_api-at2025-10-01 13:48:24.735297.csv',
 'dataset-binance_api-at2025-10-01 13:48:35.055762.csv',
 'dataset-binance_api-at2025-10-01 13:48:45.342586.csv',
 'dataset-binance_api-at2025-10-01 13:51:01.814084.csv',
 'dataset-binance_api-at2025-10-01 13:51:12.052787.csv',
 'dataset-binance_api-at2025-10-01 13:51:22.262342.csv',
 'dataset-binance_api-at2025-10-01 13:51:32.453141.csv',
 'dataset-binance_api-at2025-10-01 13:51:42.647759.csv',
 'dataset-binance_api-at2025-10-01 13:51:52.890150.csv',
 'dataset-binance_api-at2025-10-01 13:52:03.308548.csv',
 'dataset-binance_api-at2025-10-01 13:52:13.520874.csv',
 'dataset-binance_api-at2025-10-01 13:52:23.903267.csv',
 'dataset-binance_api-at2025-10-01 13:52:34.125014.csv',
 'dataset-binance_api-at2025-10-01 13:52:44.343105.csv',
 'dataset-binance_api-at2025-10-01 13:52:54.637563.csv',
 'dataset-binance_api-at2025-10-01 13:53:05.112972.csv',
 'dataset-binance_api-at2025-10-01 13:53:16.986896.csv',

In [46]:
len(file_names)

3511

In [13]:
from functools import reduce
DATASET_BINANCE_PREFIX = 'dataset-binance_api-at'
file_names = scan_files_including_regex(file_folder=FILE_FOLDER['binance'], regex=DATASET_BINANCE_PREFIX)
df_total = reduce(lambda df1, df2: df1.T.join(df2.T, how='outer', rsuffix='_duplicated').T, [load_csv_in_file_folder_by_regex(file_folder=FILE_FOLDER['binance'], regex=file_name) for file_name in file_names])
df_total

,0GBNB,0GFDUSD,0GTRY,0GUSDC,0GUSDT,1000CATBNB,1000CATFDUSD,1000CATTRY,1000CATUSDC,1000CATUSDT,...,ZROBTC,ZROFDUSD,ZROTRY,ZROUSDC,ZROUSDT,ZRXBNB,ZRXBTC,ZRXBUSD,ZRXETH,ZRXUSDT
datetime,,,,,,,,,,,,,,,,,,,,,
2025-09-22 14:12:15,NaN,NaN,NaN,NaN,NaN,0.000009,0.00793,0.329,0.00794,0.00792,...,0.000017,1.941,79.7,1.924,1.923,0.0,0.000002,0.1689,0.000099,0.2451
2025-09-22 14:36:51,NaN,NaN,NaN,NaN,NaN,0.000009,0.00793,0.329,0.00791,0.00789,...,0.000017,1.930,79.4,1.919,1.918,0.0,0.000002,0.1689,0.000099,0.2438
2025-09-22 15:13:32,NaN,NaN,NaN,NaN,NaN,0.000009,0.00731,0.311,0.00752,0.00752,...,0.000016,1.836,76.0,1.836,1.836,0.0,0.000002,0.1689,0.000099,0.2332
2025-09-22 15:13:42,NaN,NaN,NaN,NaN,NaN,0.000009,0.00731,0.312,0.00752,0.00752,...,0.000016,1.836,76.0,1.839,1.838,0.0,0.000002,0.1689,0.000099,0.2334
2025-09-22 15:13:44,NaN,NaN,NaN,NaN,NaN,0.000009,0.00731,0.312,0.00754,0.00752,...,0.000016,1.836,76.0,1.839,1.838,0.0,0.000002,0.1689,0.000099,0.2330
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-10-02 15:50:39,0.002621,2.726,112.90,2.720,2.719,0.000009,0.00770,0.318,0.00765,0.00767,...,0.000020,2.372,98.5,2.368,2.366,0.0,0.000002,0.1689,0.000099,0.2559
2025-10-02 15:50:49,0.002621,2.723,112.90,2.720,2.718,0.000009,0.00770,0.319,0.00765,0.00767,...,0.000020,2.374,98.5,2.375,2.373,0.0,0.000002,0.1689,0.000099,0.2559
2025-10-02 15:50:59,0.002621,2.723,112.90,2.719,2.717,0.000009,0.00770,0.319,0.00765,0.00767,...,0.000020,2.374,98.5,2.373,2.372,0.0,0.000002,0.1689,0.000099,0.2559
2025-10-02 15:51:09,0.002621,2.723,112.84,2.719,2.716,0.000009,0.00770,0.319,0.00765,0.00766,...,0.000020,2.374,98.5,2.371,2.368,0.0,0.000002,0.1689,0.000099,0.2559
2025-10-02 15:51:19,0.002621,2.723,112.84,2.719,2.716,0.000009,0.00770,0.319,0.00765,0.00766,...,0.000020,2.374,98.5,2.365,2.365,0.0,0.000002,0.1689,0.000099,0.2557

In [14]:
map_df_to_csv(df=df_total, file_folder=FILE_FOLDER['total'], file_name='dataset-binance_api-total.csv')

| Saved csv to data/dataset-total/dataset-binance_api-total.csv

,0GBNB,0GFDUSD,0GTRY,0GUSDC,0GUSDT,1000CATBNB,1000CATFDUSD,1000CATTRY,1000CATUSDC,1000CATUSDT,...,ZROBTC,ZROFDUSD,ZROTRY,ZROUSDC,ZROUSDT,ZRXBNB,ZRXBTC,ZRXBUSD,ZRXETH,ZRXUSDT
datetime,,,,,,,,,,,,,,,,,,,,,
2025-09-22 14:12:15,NaN,NaN,NaN,NaN,NaN,0.000009,0.00793,0.329,0.00794,0.00792,...,0.000017,1.941,79.7,1.924,1.923,0.0,0.000002,0.1689,0.000099,0.2451
2025-09-22 14:36:51,NaN,NaN,NaN,NaN,NaN,0.000009,0.00793,0.329,0.00791,0.00789,...,0.000017,1.930,79.4,1.919,1.918,0.0,0.000002,0.1689,0.000099,0.2438
2025-09-22 15:13:32,NaN,NaN,NaN,NaN,NaN,0.000009,0.00731,0.311,0.00752,0.00752,...,0.000016,1.836,76.0,1.836,1.836,0.0,0.000002,0.1689,0.000099,0.2332
2025-09-22 15:13:42,NaN,NaN,NaN,NaN,NaN,0.000009,0.00731,0.312,0.00752,0.00752,...,0.000016,1.836,76.0,1.839,1.838,0.0,0.000002,0.1689,0.000099,0.2334
2025-09-22 15:13:44,NaN,NaN,NaN,NaN,NaN,0.000009,0.00731,0.312,0.00754,0.00752,...,0.000016,1.836,76.0,1.839,1.838,0.0,0.000002,0.1689,0.000099,0.2330
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-10-02 15:50:39,0.002621,2.726,112.90,2.720,2.719,0.000009,0.00770,0.318,0.00765,0.00767,...,0.000020,2.372,98.5,2.368,2.366,0.0,0.000002,0.1689,0.000099,0.2559
2025-10-02 15:50:49,0.002621,2.723,112.90,2.720,2.718,0.000009,0.00770,0.319,0.00765,0.00767,...,0.000020,2.374,98.5,2.375,2.373,0.0,0.000002,0.1689,0.000099,0.2559
2025-10-02 15:50:59,0.002621,2.723,112.90,2.719,2.717,0.000009,0.00770,0.319,0.00765,0.00767,...,0.000020,2.374,98.5,2.373,2.372,0.0,0.000002,0.1689,0.000099,0.2559
2025-10-02 15:51:09,0.002621,2.723,112.84,2.719,2.716,0.000009,0.00770,0.319,0.00765,0.00766,...,0.000020,2.374,98.5,2.371,2.368,0.0,0.000002,0.1689,0.000099,0.2559
2025-10-02 15:51:19,0.002621,2.723,112.84,2.719,2.716,0.000009,0.00770,0.319,0.00765,0.00766,...,0.000020,2.374,98.5,2.365,2.365,0.0,0.000002,0.1689,0.000099,0.2557

In [16]:
from canonical_transformer.morphisms import map_csv_to_df

file_name =scan_files_including_regex(file_folder=FILE_FOLDER['total'], regex='.csv')[-1]
df_csv =map_csv_to_df(file_folder=FILE_FOLDER['total'], file_name=file_name)
df_csv

,0GBNB,0GFDUSD,0GTRY,0GUSDC,0GUSDT,1000CATBNB,1000CATFDUSD,1000CATTRY,1000CATUSDC,1000CATUSDT,...,ZROBTC,ZROFDUSD,ZROTRY,ZROUSDC,ZROUSDT,ZRXBNB,ZRXBTC,ZRXBUSD,ZRXETH,ZRXUSDT
datetime,,,,,,,,,,,,,,,,,,,,,
2025-09-22 14:12:15,NaN,NaN,NaN,NaN,NaN,0.000009,0.00793,0.329,0.00794,0.00792,...,0.000017,1.941,79.7,1.924,1.923,0.0,0.000002,0.1689,0.000099,0.2451
2025-09-22 14:36:51,NaN,NaN,NaN,NaN,NaN,0.000009,0.00793,0.329,0.00791,0.00789,...,0.000017,1.930,79.4,1.919,1.918,0.0,0.000002,0.1689,0.000099,0.2438
2025-09-22 15:13:32,NaN,NaN,NaN,NaN,NaN,0.000009,0.00731,0.311,0.00752,0.00752,...,0.000016,1.836,76.0,1.836,1.836,0.0,0.000002,0.1689,0.000099,0.2332
2025-09-22 15:13:42,NaN,NaN,NaN,NaN,NaN,0.000009,0.00731,0.312,0.00752,0.00752,...,0.000016,1.836,76.0,1.839,1.838,0.0,0.000002,0.1689,0.000099,0.2334
2025-09-22 15:13:44,NaN,NaN,NaN,NaN,NaN,0.000009,0.00731,0.312,0.00754,0.00752,...,0.000016,1.836,76.0,1.839,1.838,0.0,0.000002,0.1689,0.000099,0.2330
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-10-02 15:50:39,0.002621,2.726,112.90,2.720,2.719,0.000009,0.00770,0.318,0.00765,0.00767,...,0.000020,2.372,98.5,2.368,2.366,0.0,0.000002,0.1689,0.000099,0.2559
2025-10-02 15:50:49,0.002621,2.723,112.90,2.720,2.718,0.000009,0.00770,0.319,0.00765,0.00767,...,0.000020,2.374,98.5,2.375,2.373,0.0,0.000002,0.1689,0.000099,0.2559
2025-10-02 15:50:59,0.002621,2.723,112.90,2.719,2.717,0.000009,0.00770,0.319,0.00765,0.00767,...,0.000020,2.374,98.5,2.373,2.372,0.0,0.000002,0.1689,0.000099,0.2559
2025-10-02 15:51:09,0.002621,2.723,112.84,2.719,2.716,0.000009,0.00770,0.319,0.00765,0.00766,...,0.000020,2.374,98.5,2.371,2.368,0.0,0.000002,0.1689,0.000099,0.2559
2025-10-02 15:51:19,0.002621,2.723,112.84,2.719,2.716,0.000009,0.00770,0.319,0.00765,0.00766,...,0.000020,2.374,98.5,2.365,2.365,0.0,0.000002,0.1689,0.000099,0.2557

In [19]:
last_datetime_str = df_csv.index[-1]
last_datetime_str

'2025-10-02 15:51:19'

In [18]:
def extract_datetime_str_from_filename(file_name:str)->str:
    return file_name.split('at')[-1].split('.csv')[0]

DATASET_BINANCE_PREFIX = 'dataset-binance_api-at'
file_names = scan_files_including_regex(file_folder=FILE_FOLDER['binance'], regex=DATASET_BINANCE_PREFIX)
datetime_strs = [extract_datetime_str_from_filename(file_name) for file_name in file_names]
datetime_strs

['2025-09-22 14:12:15.558889',
 '2025-09-22 14:36:51.024951',
 '2025-09-22 15:13:32.437206',
 '2025-09-22 15:13:42.324450',
 '2025-09-22 15:13:44.929049',
 '2025-09-22 15:13:57.197217',
 '2025-09-22 15:14:04.108237',
 '2025-10-01 10:45:39.493475',
 '2025-10-01 10:45:43.572308',
 '2025-10-01 10:45:45.038490',
 '2025-10-01 10:45:45.870827',
 '2025-10-01 10:45:47.456667',
 '2025-10-01 10:45:49.275929',
 '2025-10-01 10:45:50.254635',
 '2025-10-01 10:45:51.168384',
 '2025-10-01 10:45:52.072152',
 '2025-10-01 10:45:52.998195',
 '2025-10-01 10:45:53.817472',
 '2025-10-01 10:45:54.834691',
 '2025-10-01 10:45:55.687214',
 '2025-10-01 10:53:32.732888',
 '2025-10-01 11:05:53.034961',
 '2025-10-01 11:06:03.214001',
 '2025-10-01 11:06:13.409766',
 '2025-10-01 11:06:23.615444',
 '2025-10-01 11:06:33.816770',
 '2025-10-01 11:06:43.976897',
 '2025-10-01 11:06:54.164687',
 '2025-10-01 11:07:04.324132',
 '2025-10-01 11:07:14.526111',
 '2025-10-01 11:07:24.709910',
 '2025-10-01 11:07:34.936393',
 '2025-10-01 11:07:45.100529',
 '2025-10-01 11:07:55.360115',
 '2025-10-01 11:08:05.536255',
 '2025-10-01 11:08:15.699199',
 '2025-10-01 11:08:25.890581',
 '2025-10-01 11:08:36.065507',
 '2025-10-01 11:08:46.212176',
 '2025-10-01 11:08:56.360178',
 '2025-10-01 11:09:06.545494',
 '2025-10-01 11:09:16.732794',
 '2025-10-01 11:09:26.874669',
 '2025-10-01 11:09:37.042067',
 '2025-10-01 11:09:47.210575',
 '2025-10-01 11:09:57.382201',
 '2025-10-01 11:10:07.535110',
 '2025-10-01 11:10:17.690720',
 '2025-10-01 11:10:27.850876',
 '2025-10-01 11:10:38.097263',
 '2025-10-01 11:10:48.275960',
 '2025-10-01 11:10:58.474196',
 '2025-10-01 11:11:08.609383',
 '2025-10-01 11:11:18.755025',
 '2025-10-01 11:11:28.888563',
 '2025-10-01 11:11:39.056709',
 '2025-10-01 11:11:49.191821',
 '2025-10-01 11:14:00.669660',
 '2025-10-01 11:14:11.330199',
 '2025-10-01 12:37:09.941490',
 '2025-10-01 12:37:20.414823',
 '2025-10-01 12:49:09.240350',
 '2025-10-01 12:49:19.558931',
 '2025-10-01 12:49:29.768361',
 '2025-10-01 12:49:39.943969',
 '2025-10-01 12:56:40.983929',
 '2025-10-01 12:56:51.322061',
 '2025-10-01 12:57:01.679620',
 '2025-10-01 12:57:11.875653',
 '2025-10-01 12:58:04.037209',
 '2025-10-01 12:58:14.405660',
 '2025-10-01 12:58:24.622651',
 '2025-10-01 12:58:34.853284',
 '2025-10-01 12:58:46.390962',
 '2025-10-01 12:58:56.586105',
 '2025-10-01 12:59:06.757927',
 '2025-10-01 12:59:16.924617',
 '2025-10-01 13:01:00.718376',
 '2025-10-01 13:01:11.232469',
 '2025-10-01 13:01:42.075645',
 '2025-10-01 13:01:52.443548',
 '2025-10-01 13:02:02.931495',
 '2025-10-01 13:02:13.111562',
 '2025-10-01 13:03:10.701921',
 '2025-10-01 13:03:21.083706',
 '2025-10-01 13:03:31.544246',
 '2025-10-01 13:03:42.660240',
 '2025-10-01 13:03:53.399241',
 '2025-10-01 13:04:04.793570',
 '2025-10-01 13:04:15.057347',
 '2025-10-01 13:04:25.279739',
 '2025-10-01 13:04:38.869161',
 '2025-10-01 13:04:49.501548',
 '2025-10-01 13:04:59.957084',
 '2025-10-01 13:05:10.399347',
 '2025-10-01 13:05:21.996818',
 '2025-10-01 13:05:32.198062',
 '2025-10-01 13:05:42.751156',
 '2025-10-01 13:05:53.092701',
 '2025-10-01 13:06:03.879166',
 '2025-10-01 13:06:14.711475',
 '2025-10-01 13:06:24.964406',
 '2025-10-01 13:06:37.947457',
 '2025-10-01 13:06:48.888449',
 '2025-10-01 13:07:00.697791',
 '2025-10-01 13:07:11.733244',
 '2025-10-01 13:07:21.994082',
 '2025-10-01 13:07:32.742785',
 '2025-10-01 13:07:42.993502',
 '2025-10-01 13:07:53.375453',
 '2025-10-01 13:08:05.647416',
 '2025-10-01 13:08:16.001365',
 '2025-10-01 13:08:50.876704',
 '2025-10-01 13:09:02.637033',
 '2025-10-01 13:09:13.391309',
 '2025-10-01 13:09:24.675636',
 '2025-10-01 13:09:35.939977',
 '2025-10-01 13:09:47.658174',
 '2025-10-01 13:09:58.898394',
 '2025-10-01 13:10:09.483793',
 '2025-10-01 13:10:24.809651',
 '2025-10-01 13:10:35.137401',
 '2025-10-01 13:10:45.930968',
 '2025-10-01 13:10:56.413773',
 '2025-10-01 13:11:06.673597',
 '2025-10-01 13:11:19.665754',
 '2025-10-01 13:11:29.928015',
 '2025-10-01 13:11:40.473656',
 '2025-10-01 13:11:50.608421',
 '2025-10-01 13:12:02.235946',
 '2025-10-01 13:12:12.508934',
 '2025-10-01 13:12:23.028914',
 '2025-10-01 13:12:34.221298',
 '2025-10-01 13:12:44.741413',
 '2025-10-01 13:12:56.744041',
 '2025-10-01 13:13:09.419102',
 '2025-10-01 13:13:20.121904',
 '2025-10-01 13:13:31.331059',
 '2025-10-01 13:13:41.697555',
 '2025-10-01 13:13:52.448531',
 '2025-10-01 13:14:02.975175',
 '2025-10-01 13:14:14.764309',
 '2025-10-01 13:14:25.006507',
 '2025-10-01 13:14:38.917103',
 '2025-10-01 13:14:56.407622',
 '2025-10-01 13:15:06.717935',
 '2025-10-01 13:15:16.955800',
 '2025-10-01 13:15:27.247958',
 '2025-10-01 13:15:40.355286',
 '2025-10-01 13:15:50.596524',
 '2025-10-01 13:16:01.026622',
 '2025-10-01 13:16:12.339518',
 '2025-10-01 13:16:22.584045',
 '2025-10-01 13:16:32.821317',
 '2025-10-01 13:16:45.769997',
 '2025-10-01 13:16:57.964636',
 '2025-10-01 13:17:09.329148',
 '2025-10-01 13:17:20.610012',
 '2025-10-01 13:17:32.050028',
 '2025-10-01 13:17:43.410994',
 '2025-10-01 13:17:53.675885',
 '2025-10-01 13:18:04.348068',
 '2025-10-01 13:18:14.659651',
 '2025-10-01 13:18:24.900409',
 '2025-10-01 13:18:35.794689',
 '2025-10-01 13:18:46.211239',
 '2025-10-01 13:18:56.425553',
 '2025-10-01 13:19:06.783184',
 '2025-10-01 13:19:17.085056',
 '2025-10-01 13:19:27.331126',
 '2025-10-01 13:19:37.700378',
 '2025-10-01 13:19:48.351050',
 '2025-10-01 13:19:58.557340',
 '2025-10-01 13:20:09.029776',
 '2025-10-01 13:20:19.241419',
 '2025-10-01 13:20:29.517433',
 '2025-10-01 13:20:39.704556',
 '2025-10-01 13:20:50.948142',
 '2025-10-01 13:21:01.313176',
 '2025-10-01 13:21:11.613412',
 '2025-10-01 13:21:21.855786',
 '2025-10-01 13:21:33.083827',
 '2025-10-01 13:21:44.912438',
 '2025-10-01 13:21:55.142309',
 '2025-10-01 13:22:05.450054',
 '2025-10-01 13:22:15.705951',
 '2025-10-01 13:22:26.290765',
 '2025-10-01 13:22:38.163255',
 '2025-10-01 13:22:48.687247',
 '2025-10-01 13:22:59.031961',
 '2025-10-01 13:23:09.681310',
 '2025-10-01 13:23:20.962303',
 '2025-10-01 13:23:32.003246',
 '2025-10-01 13:23:42.263401',
 '2025-10-01 13:23:54.560381',
 '2025-10-01 13:24:05.002567',
 '2025-10-01 13:24:15.170624',
 '2025-10-01 13:24:25.922627',
 '2025-10-01 13:24:36.165524',
 '2025-10-01 13:24:46.371683',
 '2025-10-01 13:24:56.617571',
 '2025-10-01 13:25:08.406880',
 '2025-10-01 13:25:19.146565',
 '2025-10-01 13:25:29.881586',
 '2025-10-01 13:25:41.210395',
 '2025-10-01 13:25:51.489172',
 '2025-10-01 13:26:01.764209',
 '2025-10-01 13:26:12.298378',
 '2025-10-01 13:26:23.818827',
 '2025-10-01 13:26:34.120249',
 '2025-10-01 13:26:46.147817',
 '2025-10-01 13:26:56.450598',
 '2025-10-01 13:27:07.221574',
 '2025-10-01 13:27:18.645990',
 '2025-10-01 13:27:28.857369',
 '2025-10-01 13:27:39.441597',
 '2025-10-01 13:27:51.090463',
 '2025-10-01 13:28:01.936914',
 '2025-10-01 13:28:12.556691',
 '2025-10-01 13:28:24.925590',
 '2025-10-01 13:28:46.113821',
 '2025-10-01 13:28:56.389367',
 '2025-10-01 13:29:06.635144',
 '2025-10-01 13:29:16.797774',
 '2025-10-01 13:29:27.019385',
 '2025-10-01 13:29:37.208837',
 '2025-10-01 13:29:47.422263',
 '2025-10-01 13:29:57.642338',
 '2025-10-01 13:30:07.913922',
 '2025-10-01 13:30:18.923490',
 '2025-10-01 13:30:29.172936',
 '2025-10-01 13:30:39.346667',
 '2025-10-01 13:30:49.582096',
 '2025-10-01 13:30:59.762285',
 '2025-10-01 13:31:10.786717',
 '2025-10-01 13:31:21.016715',
 '2025-10-01 13:31:31.237463',
 '2025-10-01 13:31:41.461164',
 '2025-10-01 13:31:51.643532',
 '2025-10-01 13:32:01.901981',
 '2025-10-01 13:32:12.087438',
 '2025-10-01 13:32:22.279150',
 '2025-10-01 13:32:32.572196',
 '2025-10-01 13:32:42.822490',
 '2025-10-01 13:32:53.029157',
 '2025-10-01 13:33:03.211948',
 '2025-10-01 13:33:13.463893',
 '2025-10-01 13:33:23.701004',
 '2025-10-01 13:33:33.913546',
 '2025-10-01 13:33:44.113127',
 '2025-10-01 13:33:54.374315',
 '2025-10-01 13:34:04.610927',
 '2025-10-01 13:34:14.850592',
 '2025-10-01 13:34:26.045440',
 '2025-10-01 13:34:36.293358',
 '2025-10-01 13:34:47.571650',
 '2025-10-01 13:34:57.775492',
 '2025-10-01 13:35:07.933643',
 '2025-10-01 13:35:18.186738',
 '2025-10-01 13:35:28.366454',
 '2025-10-01 13:35:38.655016',
 '2025-10-01 13:35:48.893636',
 '2025-10-01 13:35:59.098769',
 '2025-10-01 13:36:09.882646',
 '2025-10-01 13:36:20.036468',
 '2025-10-01 13:36:30.269257',
 '2025-10-01 13:36:40.489256',
 '2025-10-01 13:36:50.718234',
 '2025-10-01 13:37:01.110668',
 '2025-10-01 13:37:11.411710',
 '2025-10-01 13:37:21.743296',
 '2025-10-01 13:37:32.121223',
 '2025-10-01 13:37:43.969770',
 '2025-10-01 13:37:55.211108',
 '2025-10-01 13:38:05.657038',
 '2025-10-01 13:38:15.945904',
 '2025-10-01 13:38:26.181725',
 '2025-10-01 13:38:36.360144',
 '2025-10-01 13:38:46.586393',
 '2025-10-01 13:38:56.780004',
 '2025-10-01 13:39:07.087226',
 '2025-10-01 13:39:17.347125',
 '2025-10-01 13:39:27.670443',
 '2025-10-01 13:39:37.867455',
 '2025-10-01 13:39:48.084486',
 '2025-10-01 13:39:59.267538',
 '2025-10-01 13:40:09.474729',
 '2025-10-01 13:40:20.656316',
 '2025-10-01 13:40:34.649766',
 '2025-10-01 13:40:45.254575',
 '2025-10-01 13:40:59.712065',
 '2025-10-01 13:41:10.082852',
 '2025-10-01 13:41:20.291895',
 '2025-10-01 13:41:30.490775',
 '2025-10-01 13:41:40.706153',
 '2025-10-01 13:41:51.067127',
 '2025-10-01 13:42:01.263140',
 '2025-10-01 13:42:11.553119',
 '2025-10-01 13:42:21.761381',
 '2025-10-01 13:42:31.931921',
 '2025-10-01 13:42:42.143594',
 '2025-10-01 13:42:52.371035',
 '2025-10-01 13:43:02.726999',
 '2025-10-01 13:43:13.880435',
 '2025-10-01 13:43:24.105627',
 '2025-10-01 13:43:34.339070',
 '2025-10-01 13:43:45.026551',
 '2025-10-01 13:43:56.400713',
 '2025-10-01 13:44:06.603920',
 '2025-10-01 13:44:16.836731',
 '2025-10-01 13:44:27.093049',
 '2025-10-01 13:44:38.151588',
 '2025-10-01 13:44:48.549378',
 '2025-10-01 13:44:59.719071',
 '2025-10-01 13:45:10.007752',
 '2025-10-01 13:45:20.264675',
 '2025-10-01 13:45:30.452701',
 '2025-10-01 13:45:40.618098',
 '2025-10-01 13:45:50.868576',
 '2025-10-01 13:46:01.108870',
 '2025-10-01 13:46:11.280885',
 '2025-10-01 13:46:21.475241',
 '2025-10-01 13:46:32.007263',
 '2025-10-01 13:46:42.367345',
 '2025-10-01 13:46:52.801649',
 '2025-10-01 13:47:02.989589',
 '2025-10-01 13:47:13.225556',
 '2025-10-01 13:47:23.415248',
 '2025-10-01 13:47:33.650674',
 '2025-10-01 13:47:43.851762',
 '2025-10-01 13:47:54.050275',
 '2025-10-01 13:48:04.289229',
 '2025-10-01 13:48:14.564471',
 '2025-10-01 13:48:24.735297',
 '2025-10-01 13:48:35.055762',
 '2025-10-01 13:48:45.342586',
 '2025-10-01 13:51:01.814084',
 '2025-10-01 13:51:12.052787',
 '2025-10-01 13:51:22.262342',
 '2025-10-01 13:51:32.453141',
 '2025-10-01 13:51:42.647759',
 '2025-10-01 13:51:52.890150',
 '2025-10-01 13:52:03.308548',
 '2025-10-01 13:52:13.520874',
 '2025-10-01 13:52:23.903267',
 '2025-10-01 13:52:34.125014',
 '2025-10-01 13:52:44.343105',
 '2025-10-01 13:52:54.637563',
 '2025-10-01 13:53:05.112972',
 '2025-10-01 13:53:16.986896',
 '2025-10-01 13:53:27.182285',
 '2025-10-01 13:53:37.379900',
 '2025-10-01 13:53:48.195805',
 '2025-10-01 13:53:58.406859',
 '2025-10-01 13:54:08.603267',
 '2025-10-01 13:54:18.796101',
 '2025-10-01 13:54:29.541571',
 '2025-10-01 13:54:39.792576',
 '2025-10-01 13:54:50.643344',
 '2025-10-01 13:55:00.829763',
 '2025-10-01 13:55:10.990000',
 '2025-10-01 13:55:21.241883',
 '2025-10-01 13:55:38.515021',
 '2025-10-01 13:55:48.750552',
 '2025-10-01 13:55:58.965872',
 '2025-10-01 13:56:09.203834',
 '2025-10-01 13:56:19.419992',
 '2025-10-01 13:56:29.623637',
 '2025-10-01 13:56:39.802846',
 '2025-10-01 13:56:50.681730',
 '2025-10-01 13:57:00.877404',
 '2025-10-01 13:57:11.062187',
 '2025-10-01 13:57:21.299217',
 '2025-10-01 13:57:31.511612',
 '2025-10-01 13:57:41.763079',
 '2025-10-01 13:57:51.972224',
 '2025-10-01 13:58:02.187034',
 '2025-10-01 13:58:12.380293',
 '2025-10-01 13:58:22.570603',
 '2025-10-01 13:58:32.771173',
 '2025-10-01 13:58:42.976881',
 '2025-10-01 13:58:53.158393',
 '2025-10-01 13:59:03.426331',
 '2025-10-01 13:59:13.927546',
 '2025-10-01 13:59:24.232125',
 '2025-10-01 13:59:34.497435',
 '2025-10-01 13:59:44.699293',
 '2025-10-01 13:59:54.936421',
 '2025-10-01 14:00:06.280565',
 '2025-10-01 14:00:16.466552',
 '2025-10-01 14:00:27.399529',
 '2025-10-01 14:00:37.651086',
 '2025-10-01 14:00:47.816086',
 '2025-10-01 14:00:58.111305',
 '2025-10-01 14:01:08.314185',
 '2025-10-01 14:01:19.425577',
 '2025-10-01 14:01:29.593373',
 '2025-10-01 14:01:39.800757',
 '2025-10-01 14:01:50.493054',
 '2025-10-01 14:02:00.757643',
 '2025-10-01 14:02:10.991224',
 '2025-10-01 14:02:21.247387',
 '2025-10-01 14:02:32.617962',
 '2025-10-01 14:02:42.768009',
 '2025-10-01 14:02:52.955200',
 '2025-10-01 14:03:03.297201',
 '2025-10-01 14:03:13.452838',
 '2025-10-01 14:03:23.624686',
 '2025-10-01 14:03:33.827172',
 '2025-10-01 14:03:43.990883',
 '2025-10-01 14:03:55.037054',
 '2025-10-01 14:04:05.342690',
 '2025-10-01 14:04:15.571586',
 '2025-10-01 14:04:26.836788',
 '2025-10-01 14:04:37.657032',
 '2025-10-01 14:04:48.032160',
 '2025-10-01 14:04:58.238890',
 '2025-10-01 14:05:09.328664',
 '2025-10-01 14:05:19.485723',
 '2025-10-01 14:05:29.757918',
 '2025-10-01 14:05:40.586546',
 '2025-10-01 14:05:50.782606',
 '2025-10-01 14:06:00.992161',
 '2025-10-01 14:06:11.319267',
 '2025-10-01 14:06:21.640689',
 '2025-10-01 14:06:31.920840',
 '2025-10-01 14:06:43.601337',
 '2025-10-01 14:06:53.842535',
 '2025-10-01 14:07:04.126174',
 '2025-10-01 14:07:14.470784',
 '2025-10-01 14:07:24.649428',
 '2025-10-01 14:07:34.848242',
 '2025-10-01 14:07:45.046466',
 '2025-10-01 14:07:55.223404',
 '2025-10-01 14:08:05.474700',
 '2025-10-01 14:08:15.629105',
 '2025-10-01 14:08:25.861715',
 '2025-10-01 14:08:36.019987',
 '2025-10-01 14:08:46.212422',
 '2025-10-01 14:08:56.486851',
 '2025-10-01 14:09:06.650957',
 '2025-10-01 14:09:16.802246',
 '2025-10-01 14:09:26.976667',
 '2025-10-01 14:09:37.264569',
 '2025-10-01 14:09:47.836836',
 '2025-10-01 14:09:58.134845',
 '2025-10-01 14:10:08.303100',
 '2025-10-01 14:10:18.481116',
 '2025-10-01 14:10:28.656297',
 '2025-10-01 14:10:38.855716',
 '2025-10-01 14:10:49.102556',
 '2025-10-01 14:10:59.477832',
 '2025-10-01 14:11:09.709172',
 '2025-10-01 14:11:19.919735',
 '2025-10-01 14:11:30.134047',
 '2025-10-01 14:11:40.373425',
 '2025-10-01 14:11:50.611844',
 '2025-10-01 14:12:00.892785',
 '2025-10-01 14:12:11.075561',
 '2025-10-01 14:12:21.327686',
 '2025-10-01 14:12:31.518128',
 '2025-10-01 14:12:41.717979',
 '2025-10-01 14:12:51.929024',
 '2025-10-01 14:13:02.161661',
 '2025-10-01 14:13:12.368222',
 '2025-10-01 14:13:23.377825',
 '2025-10-01 14:13:33.698010',
 '2025-10-01 14:13:43.849996',
 '2025-10-01 14:13:54.070803',
 '2025-10-01 14:14:04.270562',
 '2025-10-01 14:14:14.522067',
 '2025-10-01 14:14:24.670699',
 '2025-10-01 14:14:34.849387',
 '2025-10-01 14:14:45.086344',
 '2025-10-01 14:14:55.227791',
 '2025-10-01 14:15:05.510589',
 '2025-10-01 14:15:15.725528',
 '2025-10-01 14:15:25.992591',
 '2025-10-01 14:15:37.089128',
 '2025-10-01 14:15:47.323863',
 '2025-10-01 14:15:57.503631',
 '2025-10-01 14:16:07.675637',
 '2025-10-01 14:16:17.835197',
 '2025-10-01 14:16:28.007991',
 '2025-10-01 14:16:38.264094',
 '2025-10-01 14:16:48.450691',
 '2025-10-01 14:17:00.390513',
 '2025-10-01 14:17:10.556151',
 '2025-10-01 14:17:20.728340',
 '2025-10-01 14:17:30.873986',
 '2025-10-01 14:17:41.150175',
 '2025-10-01 14:17:52.221574',
 '2025-10-01 14:18:02.435009',
 '2025-10-01 14:18:12.742458',
 '2025-10-01 14:18:22.932925',
 '2025-10-01 14:18:33.114449',
 '2025-10-01 14:18:43.339145',
 '2025-10-01 14:18:53.546054',
 '2025-10-01 14:19:03.704265',
 '2025-10-01 14:19:13.978538',
 '2025-10-01 14:19:24.142380',
 '2025-10-01 14:19:34.425181',
 '2025-10-01 14:19:44.619160',
 '2025-10-01 14:19:54.927963',
 '2025-10-01 14:20:05.276011',
 '2025-10-01 14:20:15.493809',
 '2025-10-01 14:20:25.721048',
 '2025-10-01 14:20:35.902470',
 '2025-10-01 14:20:46.170036',
 '2025-10-01 14:20:56.625168',
 '2025-10-01 14:21:06.803158',
 '2025-10-01 14:21:16.969813',
 '2025-10-01 14:21:27.164136',
 '2025-10-01 14:21:37.450741',
 '2025-10-01 14:21:47.723252',
 '2025-10-01 14:21:57.928662',
 '2025-10-01 14:22:08.130831',
 '2025-10-01 14:22:18.336567',
 '2025-10-01 14:22:28.501906',
 '2025-10-01 14:22:38.691019',
 '2025-10-01 14:22:48.882797',
 '2025-10-01 14:22:59.063221',
 '2025-10-01 14:23:09.225160',
 '2025-10-01 14:23:19.398622',
 '2025-10-01 14:23:29.553474',
 '2025-10-01 14:23:39.765407',
 '2025-10-01 14:23:49.932264',
 '2025-10-01 14:24:00.076277',
 '2025-10-01 14:24:10.241738',
 '2025-10-01 14:24:20.408158',
 '2025-10-01 14:24:30.618334',
 '2025-10-01 14:24:40.793831',
 '2025-10-01 14:24:50.973557',
 '2025-10-01 14:25:01.134728',
 '2025-10-01 14:25:11.351235',
 '2025-10-01 14:25:21.581224',
 '2025-10-01 14:25:31.790154',
 '2025-10-01 14:25:41.960473',
 '2025-10-01 14:25:52.410942',
 '2025-10-01 14:26:02.640203',
 '2025-10-01 14:26:12.779853',
 '2025-10-01 14:26:22.939953',
 '2025-10-01 14:26:33.108222',
 '2025-10-01 14:26:43.319676',
 '2025-10-01 14:26:53.532287',
 '2025-10-01 14:27:03.694067',
 '2025-10-01 14:27:13.840422',
 '2025-10-01 14:27:24.051698',
 '2025-10-01 14:27:34.206853',
 '2025-10-01 14:27:44.375922',
 '2025-10-01 14:27:54.561063',
 '2025-10-01 14:28:04.787160',
 '2025-10-01 14:28:14.968666',
 '2025-10-01 14:28:25.141533',
 '2025-10-01 14:28:35.449611',
 '2025-10-01 14:28:45.642732',
 '2025-10-01 14:28:56.669609',
 '2025-10-01 14:29:06.862705',
 '2025-10-01 14:29:17.022230',
 '2025-10-01 14:29:27.169223',
 '2025-10-01 14:29:37.356759',
 '2025-10-01 14:29:47.528305',
 '2025-10-01 14:29:57.708093',
 '2025-10-01 14:30:07.896646',
 '2025-10-01 14:30:18.075801',
 '2025-10-01 14:30:28.219179',
 '2025-10-01 14:30:38.369753',
 '2025-10-01 14:30:48.546908',
 '2025-10-01 14:30:58.718607',
 '2025-10-01 14:31:09.004439',
 '2025-10-01 14:31:19.174669',
 '2025-10-01 14:31:29.394580',
 '2025-10-01 14:31:39.544309',
 '2025-10-01 14:31:49.703785',
 '2025-10-01 14:31:59.876067',
 '2025-10-01 14:32:10.051767',
 '2025-10-01 14:32:20.206936',
 '2025-10-01 14:32:30.693065',
 '2025-10-01 14:32:40.850323',
 '2025-10-01 14:32:51.097422',
 '2025-10-01 14:33:01.293988',
 '2025-10-01 14:33:11.528470',
 '2025-10-01 14:33:22.647299',
 '2025-10-01 14:33:32.786961',
 '2025-10-01 14:33:42.962837',
 '2025-10-01 14:33:53.114046',
 '2025-10-01 14:34:03.321427',
 '2025-10-01 14:34:13.518566',
 '2025-10-01 14:34:23.672468',
 '2025-10-01 14:34:33.836959',
 '2025-10-01 14:34:44.083674',
 '2025-10-01 14:34:54.255231',
 '2025-10-01 14:35:04.453716',
 '2025-10-01 14:35:14.702083',
 '2025-10-01 14:35:24.912298',
 '2025-10-01 14:35:35.169248',
 '2025-10-01 14:35:45.438651',
 '2025-10-01 14:35:55.615949',
 '2025-10-01 14:36:05.874679',
 '2025-10-01 14:36:16.037648',
 '2025-10-01 14:36:26.199891',
 '2025-10-01 14:36:36.346366',
 '2025-10-01 14:36:46.510594',
 '2025-10-01 14:36:57.510595',
 '2025-10-01 14:37:07.677262',
 '2025-10-01 14:37:17.851230',
 '2025-10-01 14:37:28.014948',
 '2025-10-01 14:37:38.251024',
 '2025-10-01 14:37:48.477189',
 '2025-10-01 14:37:58.684835',
 '2025-10-01 14:38:08.853674',
 '2025-10-01 14:38:19.026316',
 '2025-10-01 14:38:29.233392',
 '2025-10-01 14:38:39.413020',
 '2025-10-01 14:38:49.611891',
 '2025-10-01 14:38:59.790683',
 '2025-10-01 14:39:10.027357',
 '2025-10-01 14:39:20.175964',
 '2025-10-01 14:39:30.370704',
 '2025-10-01 14:39:40.553317',
 '2025-10-01 14:39:50.728831',
 '2025-10-01 14:40:01.012561',
 '2025-10-01 14:40:11.182454',
 '2025-10-01 14:40:21.360614',
 '2025-10-01 14:40:31.532582',
 '2025-10-01 14:40:41.684862',
 '2025-10-01 14:40:51.837225',
 '2025-10-01 14:41:01.970206',
 '2025-10-01 14:41:12.159170',
 '2025-10-01 14:41:22.370267',
 '2025-10-01 14:41:32.543454',
 '2025-10-01 14:41:42.751628',
 '2025-10-01 14:41:52.952640',
 '2025-10-01 14:42:03.137305',
 '2025-10-01 14:42:13.360463',
 '2025-10-01 14:42:23.600436',
 '2025-10-01 14:42:33.770300',
 '2025-10-01 14:42:43.978348',
 '2025-10-01 14:42:54.185132',
 '2025-10-01 14:43:04.348816',
 '2025-10-01 14:43:14.518202',
 '2025-10-01 14:43:24.710946',
 '2025-10-01 14:43:34.911910',
 '2025-10-01 14:43:45.077472',
 '2025-10-01 14:43:55.249360',

In [21]:
dfs_new = [load_csv_in_file_folder_by_regex(file_folder=FILE_FOLDER['binance'], regex=datetime_str) for datetime_str in datetime_strs]
dfs_new

[                      ETHBTC    LTCBTC    BNBBTC    NEOBTC  QTUMETH    EOSETH  \
 datetime
 2025-09-22 14:12:15  0.03747  0.000969  0.009016  0.000055  0.00053  0.000307

                        SNTETH    BNTETH  BCCBTC    GASBTC  ...  ZKCTRY  \
 datetime                                                   ...
 2025-09-22 14:12:15  0.000017  0.000203     0.0  0.000027  ...    31.9

                            SKYBTC  SKYTRY  SKYUSDC  SKYUSDT  BARDUSDT  \
 datetime
 2025-09-22 14:12:15  5.900000e-07   2.781  0.06722  0.06716    0.9691

                      BARDUSDC  BARDFDUSD  BARDTRY   BARDBNB
 datetime
 2025-09-22 14:12:15      0.97     0.9648    40.16  0.000947

 [1 rows x 3279 columns],
                       ETHBTC    LTCBTC  BNBBTC    NEOBTC  QTUMETH    EOSETH  \
 datetime
 2025-09-22 14:36:51  0.03746  0.000968   0.009  0.000055  0.00053  0.000307

                        SNTETH    BNTETH  BCCBTC    GASBTC  ...  ZKCTRY  \
 datetime                                                   ...
 2025-09-22 14:36:51  0.000017  0.000203     0.0  0.000028  ...   31.63

                            SKYBTC  SKYTRY  SKYUSDC  SKYUSDT  BARDUSDT  \
 datetime
 2025-09-22 14:36:51  5.900000e-07   2.778  0.06706  0.06702    0.9621

                      BARDUSDC  BARDFDUSD  BARDTRY   BARDBNB
 datetime
 2025-09-22 14:36:51    0.9625     0.9635    39.88  0.000947

 [1 rows x 3279 columns],
                       ETHBTC    LTCBTC    BNBBTC    NEOBTC   QTUMETH  \
 datetime
 2025-09-22 15:13:32  0.03675  0.000943  0.008953  0.000053  0.000522

                        EOSETH    SNTETH    BNTETH  BCCBTC    GASBTC  ...  \
 datetime                                                             ...
 2025-09-22 15:13:32  0.000307  0.000017  0.000203     0.0  0.000027  ...

                      ZKCTRY        SKYBTC  SKYTRY  SKYUSDC  SKYUSDT  BARDUSDT  \
 datetime
 2025-09-22 15:13:32   30.32  5.800000e-07   2.719  0.06574  0.06569    0.9245

                      BARDUSDC  BARDFDUSD  BARDTRY   BARDBNB
 datetime
 2025-09-22 15:13:32     0.926       0.93    38.32  0.000911

 [1 rows x 3279 columns],
                       ETHBTC    LTCBTC    BNBBTC    NEOBTC   QTUMETH  \
 datetime
 2025-09-22 15:13:42  0.03675  0.000943  0.008956  0.000053  0.000522

                        EOSETH    SNTETH    BNTETH  BCCBTC    GASBTC  ...  \
 datetime                                                             ...
 2025-09-22 15:13:42  0.000307  0.000017  0.000203     0.0  0.000027  ...

                      ZKCTRY        SKYBTC  SKYTRY  SKYUSDC  SKYUSDT  BARDUSDT  \
 datetime
 2025-09-22 15:13:42   30.41  5.800000e-07   2.719  0.06585  0.06582    0.9241

                      BARDUSDC  BARDFDUSD  BARDTRY   BARDBNB
 datetime
 2025-09-22 15:13:42    0.9255       0.93    38.31  0.000911

 [1 rows x 3279 columns],
                       ETHBTC    LTCBTC    BNBBTC    NEOBTC   QTUMETH  \
 datetime
 2025-09-22 15:13:44  0.03675  0.000943  0.008958  0.000053  0.000522

                        EOSETH    SNTETH    BNTETH  BCCBTC    GASBTC  ...  \
 datetime                                                             ...
 2025-09-22 15:13:44  0.000307  0.000017  0.000203     0.0  0.000027  ...

                      ZKCTRY        SKYBTC  SKYTRY  SKYUSDC  SKYUSDT  BARDUSDT  \
 datetime
 2025-09-22 15:13:44   30.41  5.800000e-07   2.719  0.06585   0.0658    0.9241

                      BARDUSDC  BARDFDUSD  BARDTRY   BARDBNB
 datetime
 2025-09-22 15:13:44    0.9249       0.93     38.3  0.000911

 [1 rows x 3279 columns],
                       ETHBTC    LTCBTC    BNBBTC    NEOBTC   QTUMETH  \
 datetime
 2025-09-22 15:13:57  0.03676  0.000944  0.008963  0.000053  0.000522

                        EOSETH    SNTETH    BNTETH  BCCBTC    GASBTC  ...  \
 datetime                                                             ...
 2025-09-22 15:13:57  0.000307  0.000017  0.000203     0.0  0.000027  ...

                      ZKCTRY        SKYBTC  SKYTRY  SKYUSDC  SKYUSDT  BARDUSDT  \
 datetime
 2025-09-22 15:13:57   30.44  5.800000e-07   2.719    0.066  0.06596    0.9263

                      BARDUSDC  BARDFDUSD  BARDTRY   BARDBNB
 datetime
 2025-09-22 15:13:57    0.9276       0.93     38.4  0.000911

 [1 rows x 3279 columns],
                       ETHBTC    LTCBTC    BNBBTC    NEOBTC   QTUMETH  \
 datetime
 2025-09-22 15:14:04  0.03676  0.000944  0.008966  0.000053  0.000522

                        EOSETH    SNTETH    BNTETH  BCCBTC    GASBTC  ...  \
 datetime                                                             ...
 2025-09-22 15:14:04  0.000307  0.000017  0.000203     0.0  0.000027  ...

                      ZKCTRY        SKYBTC  SKYTRY  SKYUSDC  SKYUSDT  BARDUSDT  \
 datetime
 2025-09-22 15:14:04   30.44  5.800000e-07   2.719  0.06619  0.06612     0.926

                      BARDUSDC  BARDFDUSD  BARDTRY   BARDBNB
 datetime
 2025-09-22 15:14:04    0.9267       0.93    38.36  0.000911

 [1 rows x 3279 columns],
                       ETHBTC    LTCBTC    BNBBTC   NEOBTC   QTUMETH    EOSETH  \
 datetime
 2025-10-01 10:45:39  0.03641  0.000933  0.008864  0.00005  0.000511  0.000307

                        SNTETH    BNTETH  BCCBTC    GASBTC  ...  FFFDUSD  \
 datetime                                                   ...
 2025-10-01 10:45:39  0.000017  0.000203     0.0  0.000025  ...   0.1966

                      FFTRY  AEVOUSDC  MEUSDC  SNXUSDC  EDENUSDT  EDENUSDC  \
 datetime
 2025-10-01 10:45:39  8.158    0.1096   0.584    1.093    0.4508    0.4523

                       EDENBNB  EDENFDUSD  EDENTRY
 datetime
 2025-10-01 10:45:39  0.000427     0.4249     18.8

 [1 rows x 3315 columns],
                       ETHBTC    LTCBTC    BNBBTC   NEOBTC   QTUMETH    EOSETH  \
 datetime
 2025-10-01 10:45:43  0.03641  0.000933  0.008864  0.00005  0.000511  0.000307

                        SNTETH    BNTETH  BCCBTC    GASBTC  ...  FFFDUSD  \
 datetime                                                   ...
 2025-10-01 10:45:43  0.000017  0.000203     0.0  0.000025  ...   0.1966

                      FFTRY  AEVOUSDC  MEUSDC  SNXUSDC  EDENUSDT  EDENUSDC  \
 datetime
 2025-10-01 10:45:43  8.172    0.1096   0.584    1.093    0.4513    0.4518

                       EDENBNB  EDENFDUSD  EDENTRY
 datetime
 2025-10-01 10:45:43  0.000427     0.4249    18.73

 [1 rows x 3315 columns],
                       ETHBTC    LTCBTC    BNBBTC   NEOBTC   QTUMETH    EOSETH  \
 datetime
 2025-10-01 10:45:45  0.03641  0.000933  0.008864  0.00005  0.000511  0.000307

                        SNTETH    BNTETH  BCCBTC    GASBTC  ...  FFFDUSD  \
 datetime                                                   ...
 2025-10-01 10:45:45  0.000017  0.000203     0.0  0.000025  ...   0.1966

                      FFTRY  AEVOUSDC  MEUSDC  SNXUSDC  EDENUSDT  EDENUSDC  \
 datetime
 2025-10-01 10:45:45  8.196    0.1096   0.584    1.093     0.451    0.4517

                       EDENBNB  EDENFDUSD  EDENTRY
 datetime
 2025-10-01 10:45:45  0.000427     0.4249    18.76

 [1 rows x 3315 columns],
                       ETHBTC    LTCBTC    BNBBTC   NEOBTC   QTUMETH    EOSETH  \
 datetime
 2025-10-01 10:45:45  0.03641  0.000933  0.008864  0.00005  0.000511  0.000307

                        SNTETH    BNTETH  BCCBTC    GASBTC  ...  FFFDUSD  \
 datetime                                                   ...
 2025-10-01 10:45:45  0.000017  0.000203     0.0  0.000025  ...    0.198

                      FFTRY  AEVOUSDC  MEUSDC  SNXUSDC  EDENUSDT  EDENUSDC  \
 datetime
 2025-10-01 10:45:45   8.22    0.1096   0.584    1.093    0.4521     0.453

                       EDENBNB  EDENFDUSD  EDENTRY
 datetime
 2025-10-01 10:45:45  0.000427     0.4249    18.79

 [1 rows x 3315 columns],
                       ETHBTC    LTCBTC    BNBBTC   NEOBTC   QTUMETH    EOSETH  \
 datetime
 2025-10-01 10:45:47  0.03641  0.000933  0.008864  0.00005  0.000511  0.000307

                        SNTETH    BNTETH  BCCBTC    GASBTC  ...  FFFDUSD  \
 datetime                                                   ...
 2025-10-01 10:45:47  0.000017  0.000203     0.0  0.000025  ...    0.198

                      FFTRY  AEVOUSDC  MEUSDC  SNXUSDC  EDENUSDT  EDENUSDC  \
 datetime
 2025-10-01 10:45:47  8.215    0.1096   0.584    1.093    0.4525     0.453

                       EDENBNB  EDENFDUSD  EDENTRY
 datetime
 2025-10-01 10:45:47  0.000427     0.4249    18.79

 [1 rows x 3315 columns],
                       ETHBTC    LTCBTC    BNBBTC   NEOBTC   QTUMETH    EOSETH  \
 datetime
 2025-10-01 10:45:49  0.03641  0.000933  0.008864  0.00005  0.000511  0.000307

                        SNTETH    BNTETH  BCCBTC    GASBTC  ...  FFFDUSD  \
 datetime                                                   ...
 2025-10-01 10:45:49  0.000017  0.000203     0.0  0.000025  ...    0.198

                      FFTRY  AEVOUSDC  MEUSDC  SNXUSDC  EDENUSDT  EDENUSDC  \
 datetime
 2025-10-01 10:45:49  8.226    0.1096   0.584    1.093    0.4525    0.4523

                       EDENBNB  EDENFDUSD  EDENTRY
 datetime
 2025-10-01 10:45:49  0.000427     0.4249    18.79

 [1 rows x 3315 columns],
                       ETHBTC    LTCBTC    BNBBTC   NEOBTC   QTUMETH    EOSETH  \
 datetime
 2025-10-01 10:45:50  0.03641  0.000933  0.008864  0.00005  0.000511  0.000307

                        SNTETH    BNTETH  BCCBTC    GASBTC  ...  FFFDUSD  \
 datetime                                                   ...
 2025-10-01 10:45:50  0.000017  0.000203     0.0  0.000025  ...    0.198

                      FFTRY  AEVOUSDC  MEUSDC  SNXUSDC  EDENUSDT  EDENUSDC  \
 datetime
 2025-10-01 10:45:50  8.226    0.1096   0.584    1.093    0.4521    0.4523

                       EDENBNB  EDENFDUSD  EDENTRY
 datetime
 2025-10-01 10:45:50  0.000427     0.4249    18.79

 [1 rows x 3315 columns],
                       ETHBTC    LTCBTC    BNBBTC   NEOBTC   QTUMETH    EOSETH  \
 datetime
 2025-10-01 10:45:51  0.03641  0.000933  0.008864  0.00005  0.000511  0.000307

                        SNTETH    BNTETH  BCCBTC    GASBTC  ...  FFFDUSD  \
 datetime                                                   ...
 2025-10-01 10:45:51  0.000017  0.000203     0.0  0.000025  ...    0.198

                      FFTRY  AEVOUSDC  MEUSDC  SNXUSDC  EDENUSDT  EDENUSDC  \
 datetime
 2025-10-01 10:45:51  8.226    0.1096   0.584    1.093    0.4524    0.4523

                       EDENBNB  EDENFDUSD  EDENTRY
 datetime
 2025-10-01 10:45:51  0.000427     0.4249    18.79

 [1 rows x 3315 columns],
                       ETHBTC    LTCBTC    BNBBTC   NEOBTC   QTUMETH    EOSETH  \
 datetime
 2025-10-01 10:45:52  0.03642  0.000933  0.008864  0.00005  0.000511  0.000307

                        SNTETH    BNTETH  BCCBTC    GASBTC  ...  FFFDUSD  \
 datetime                                                   ...
 2025-10-01 10:45:52  0.000017  0.000203     0.0  0.000025  ...    0.198

                      FFTRY  AEVOUSDC  MEUSDC  SNXUSDC  EDENUSDT  EDENUSDC  \
 datetime
 2025-10-01 10:45:52  8.226    0.1096   0.584    1.093    0.4526    0.4523

                       EDENBNB  EDENFDUSD  EDENTRY
 datetime
 2025-10-01 10:45:52  0.000427     0.4249    18.79

 [1 rows x 3315 columns],
                       ETHBTC    LTCBTC    BNBBTC   NEOBTC   QTUMETH    EOSETH  \
 datetime
 2025-10-01 10:45:52  0.03642  0.000933  0.008864  0.00005  0.000511  0.000307

                        SNTETH    BNTETH  BCCBTC    GASBTC  ...  FFFDUSD  \
 datetime                                                   ...
 2025-10-01 10:45:52  0.000017  0.000203     0.0  0.000025  ...    0.198

                      FFTRY  AEVOUSDC  MEUSDC  SNXUSDC  EDENUSDT  EDENUSDC  \
 datetime
 2025-10-01 10:45:52  8.223    0.1096   0.584    1.093     0.453    0.4523

                       EDENBNB  EDENFDUSD  EDENTRY
 datetime
 2025-10-01 10:45:52  0.000427     0.4249    18.83

 [1 rows x 3315 columns],
                       ETHBTC    LTCBTC    BNBBTC   NEOBTC   QTUMETH    EOSETH  \
 datetime
 2025-10-01 10:45:53  0.03642  0.000933  0.008864  0.00005  0.000511  0.000307

                        SNTETH    BNTETH  BCCBTC    GASBTC  ...  FFFDUSD  \
 datetime                                                   ...
 2025-10-01 10:45:53  0.000017  0.000203     0.0  0.000025  ...    0.198

                      FFTRY  AEVOUSDC  MEUSDC  SNXUSDC  EDENUSDT  EDENUSDC  \
 datetime
 2025-10-01 10:45:53  8.222    0.1096   0.584    1.093    0.4531    0.4523

                       EDENBNB  EDENFDUSD  EDENTRY
 datetime
 2025-10-01 10:45:53  0.000427     0.4249    18.82

 [1 rows x 3315 columns],
                       ETHBTC    LTCBTC    BNBBTC   NEOBTC   QTUMETH    EOSETH  \
 datetime
 2025-10-01 10:45:54  0.03642  0.000933  0.008864  0.00005  0.000511  0.000307

                        SNTETH    BNTETH  BCCBTC    GASBTC  ...  FFFDUSD  \
 datetime                                                   ...
 2025-10-01 10:45:54  0.000017  0.000203     0.0  0.000025  ...    0.198

                      FFTRY  AEVOUSDC  MEUSDC  SNXUSDC  EDENUSDT  EDENUSDC  \
 datetime
 2025-10-01 10:45:54  8.222    0.1096   0.584    1.093    0.4531    0.4523

                       EDENBNB  EDENFDUSD  EDENTRY
 datetime
 2025-10-01 10:45:54  0.000427     0.4249    18.81

 [1 rows x 3315 columns],
                       ETHBTC    LTCBTC    BNBBTC   NEOBTC   QTUMETH    EOSETH  \
 datetime
 2025-10-01 10:45:55  0.03642  0.000933  0.008864  0.00005  0.000511  0.000307

                        SNTETH    BNTETH  BCCBTC    GASBTC  ...  FFFDUSD  \
 datetime                                                   ...
 2025-10-01 10:45:55  0.000017  0.000203     0.0  0.000025  ...    0.198

                      FFTRY  AEVOUSDC  MEUSDC  SNXUSDC  EDENUSDT  EDENUSDC  \
 datetime
 2025-10-01 10:45:55  8.222    0.1096   0.584    1.093    0.4524    0.4523

                       EDENBNB  EDENFDUSD  EDENTRY
 datetime
 2025-10-01 10:45:55  0.000427     0.4249    18.81

 [1 rows x 3315 columns],
                       ETHBTC    LTCBTC    BNBBTC    NEOBTC   QTUMETH  \
 datetime
 2025-10-01 10:53:32  0.03644  0.000934  0.008865  0.000051  0.000511

                        EOSETH    SNTETH    BNTETH  BCCBTC    GASBTC  ...  \
 datetime                                                             ...
 2025-10-01 10:53:32  0.000307  0.000017  0.000203     0.0  0.000025  ...

                      FFFDUSD  FFTRY  AEVOUSDC  MEUSDC  SNXUSDC  EDENUSDT  \
 datetime
 2025-10-01 10:53:32  0.19861  8.256    0.1106   0.584    1.093    0.4375

                      EDENUSDC   EDENBNB  EDENFDUSD  EDENTRY
 datetime
 2025-10-01 10:53:32    0.4378  0.000438     0.4455    18.18

 [1 rows x 3315 columns],
                       ETHBTC    LTCBTC    BNBBTC    NEOBTC   QTUMETH  \
 datetime
 2025-10-01 11:05:53  0.03637  0.000933  0.008858  0.000051  0.000511

                        EOSETH    SNTETH    BNTETH  BCCBTC    GASBTC  ...  \
 datetime                                                             ...
 2025-10-01 11:05:53  0.000307  0.000017  0.000203     0.0  0.000025  ...

                      FFFDUSD  FFTRY  AEVOUSDC  MEUSDC  SNXUSDC  EDENUSDT  \
 datetime
 2025-10-01 11:05:53   0.1956  8.148    0.1106   0.584     1.09    0.4362

                      EDENUSDC  EDENBNB  EDENFDUSD  EDENTRY
 datetime
 2025-10-01 11:05:53    0.4366  0.00043     0.4351    18.12

 [1 rows x 3315 columns],
                       ETHBTC    LTCBTC    BNBBTC    NEOBTC   QTUMETH  \
 datetime
 2025-10-01 11:06:03  0.03637  0.000933  0.008858  0.000051  0.000511

                        EOSETH    SNTETH    BNTETH  BCCBTC    GASBTC  ...  \
 datetime                                                             ...
 2025-10-01 11:06:03  0.000307  0.000017  0.000203     0.0  0.000025  ...

                      FFFDUSD  FFTRY  AEVOUSDC  MEUSDC  SNXUSDC  EDENUSDT  \
 datetime
 2025-10-01 11:06:03   0.1956  8.147    0.1106   0.584     1.09    0.4376

                      EDENUSDC  EDENBNB  EDENFDUSD  EDENTRY
 datetime
 2025-10-01 11:06:03    0.4371  0.00043     0.4351    18.19

 [1 rows x 3315 columns],
                       ETHBTC    LTCBTC    BNBBTC    NEOBTC   QTUMETH  \
 datetime
 2025-10-01 11:06:13  0.03637  0.000933  0.008859  0.000051  0.000511

                        EOSETH    SNTETH    BNTETH  BCCBTC    GASBTC  ...  \
 datetime                                                             ...
 2025-10-01 11:06:13  0.000307  0.000017  0.000203     0.0  0.000025  ...

                      FFFDUSD  FFTRY  AEVOUSDC  MEUSDC  SNXUSDC  EDENUSDT  \
 datetime
 2025-10-01 11:06:13    0.197   8.16    0.1106   0.584     1.09    0.4358

                      EDENUSDC  EDENBNB  EDENFDUSD  EDENTRY
 datetime
 2025-10-01 11:06:13    0.4364  0.00043     0.4351    18.18

 [1 rows x 3315 columns],
                       ETHBTC    LTCBTC    BNBBTC    NEOBTC   QTUMETH  \
 datetime
 2025-10-01 11:06:23  0.03637  0.000933  0.008859  0.000051  0.000511

                        EOSETH    SNTETH    BNTETH  BCCBTC    GASBTC  ...  \
 datetime                                                             ...
 2025-10-01 11:06:23  0.000307  0.000017  0.000203     0.0  0.000025  ...

                      FFFDUSD  FFTRY  AEVOUSDC  MEUSDC  SNXUSDC  EDENUSDT  \
 datetime
 2025-10-01 11:06:23  0.19693  8.169    0.1106   0.584     1.09      0.44

                      EDENUSDC   EDENBNB  EDENFDUSD  EDENTRY
 datetime
 2025-10-01 11:06:23    0.4396  0.000431     0.4399    18.25

 [1 rows x 3315 columns],
                       ETHBTC    LTCBTC   BNBBTC    NEOBTC   QTUMETH    EOSETH  \
 datetime
 2025-10-01 11:06:33  0.03637  0.000933  0.00886  0.000051  0.000511  0.000307

                        SNTETH    BNTETH  BCCBTC    GASBTC  ...  FFFDUSD  \
 datetime                                                   ...
 2025-10-01 11:06:33  0.000017  0.000203     0.0  0.000025  ...  0.19707

                      FFTRY  AEVOUSDC  MEUSDC  SNXUSDC  EDENUSDT  EDENUSDC  \
 datetime
 2025-10-01 11:06:33   8.18    0.1106   0.584     1.09    0.4375    0.4388

                       EDENBNB  EDENFDUSD  EDENTRY
 datetime
 2025-10-01 11:06:33  0.000431     0.4399    18.22

 [1 rows x 3315 columns],
                       ETHBTC    LTCBTC    BNBBTC    NEOBTC   QTUMETH  \
 datetime
 2025-10-01 11:06:43  0.03637  0.000933  0.008859  0.000051  0.000511

                        EOSETH    SNTETH    BNTETH  BCCBTC    GASBTC  ...  \
 datetime                                                             ...
 2025-10-01 11:06:43  0.000307  0.000017  0.000203     0.0  0.000025  ...

                      FFFDUSD  FFTRY  AEVOUSDC  MEUSDC  SNXUSDC  EDENUSDT  \
 datetime
 2025-10-01 11:06:43   0.1974  8.182    0.1106   0.584     1.09    0.4396

                      EDENUSDC   EDENBNB  EDENFDUSD  EDENTRY
 datetime
 2025-10-01 11:06:43    0.4393  0.000431     0.4399    18.28

 [1 rows x 3315 columns],
                       ETHBTC    LTCBTC    BNBBTC    NEOBTC   QTUMETH  \
 datetime
 2025-10-01 11:06:54  0.03637  0.000933  0.008859  0.000051  0.000511

                        EOSETH    SNTETH    BNTETH  BCCBTC    GASBTC  ...  \
 datetime                                                             ...
 2025-10-01 11:06:54  0.000307  0.000017  0.000203     0.0  0.000025  ...

                      FFFDUSD  FFTRY  AEVOUSDC  MEUSDC  SNXUSDC  EDENUSDT  \
 datetime
 2025-10-01 11:06:54   0.1976  8.199    0.1106   0.584     1.09    0.4409

                      EDENUSDC   EDENBNB  EDENFDUSD  EDENTRY
 datetime
 2025-10-01 11:06:54    0.4409  0.000434     0.4399    18.33

 [1 rows x 3315 columns],
                       ETHBTC    LTCBTC    BNBBTC    NEOBTC   QTUMETH  \
 datetime
 2025-10-01 11:07:04  0.03637  0.000933  0.008859  0.000051  0.000511

                        EOSETH    SNTETH    BNTETH  BCCBTC    GASBTC  ...  \
 datetime                                                             ...
 2025-10-01 11:07:04  0.000307  0.000017  0.000203     0.0  0.000025  ...

                      FFFDUSD  FFTRY  AEVOUSDC  MEUSDC  SNXUSDC  EDENUSDT  \
 datetime

In [20]:
new_datetime_strs = [datetime_str for datetime_str in datetime_strs if datetime_str > last_datetime_str]
new_datetime_strs

['2025-10-02 15:51:19.787213',
 '2025-10-02 15:51:29.924022',
 '2025-10-02 15:51:40.051977',
 '2025-10-02 15:51:50.180708',
 '2025-10-02 15:52:00.303370',
 '2025-10-02 15:52:10.427562',
 '2025-10-02 15:52:20.798450',
 '2025-10-02 15:52:30.918526',
 '2025-10-02 15:52:41.075370',
 '2025-10-02 15:52:51.195120',
 '2025-10-02 15:53:01.316489',
 '2025-10-02 15:53:11.495719',
 '2025-10-02 15:53:21.622949',
 '2025-10-02 15:53:31.746650',
 '2025-10-02 15:53:41.908120',
 '2025-10-02 15:53:52.047627',
 '2025-10-02 15:54:02.185696',
 '2025-10-02 15:54:12.345353',
 '2025-10-02 15:54:22.523004',
 '2025-10-02 15:54:32.662422',
 '2025-10-02 15:54:42.815620',
 '2025-10-02 15:54:52.966253',
 '2025-10-02 15:55:03.117685',
 '2025-10-02 15:55:13.242001',
 '2025-10-02 15:55:23.368014',
 '2025-10-02 15:55:33.526582',
 '2025-10-02 15:55:43.766571',
 '2025-10-02 15:55:53.893027',
 '2025-10-02 15:56:04.047403',
 '2025-10-02 15:56:14.218687',
 '2025-10-02 15:56:24.386764',
 '2025-10-02 15:56:34.613143',
 '2025-10-02 15:56:44.841935',
 '2025-10-02 15:56:54.976387',
 '2025-10-02 15:57:05.171655',
 '2025-10-02 15:57:15.306908']

In [10]:
row = load_csv_in_file_folder_by_regex(file_folder=FILE_FOLDER['binance'], regex=DATASET_BINANCE_PREFIX)
row

,ETHBTC,LTCBTC,BNBBTC,NEOBTC,QTUMETH,EOSETH,SNTETH,BNTETH,BCCBTC,GASBTC,...,SNXUSDC,EDENUSDT,EDENUSDC,EDENBNB,EDENFDUSD,EDENTRY,NOMFDUSD,NOMTRY,NOMUSDC,NOMUSDT
datetime,,,,,,,,,,,,,,,,,,,,,
2025-10-02 15:46:45,0.03713,0.000996,0.00875,0.000052,0.000516,0.000307,0.000017,0.000203,0.0,0.000026,...,1.293,0.3809,0.3808,0.000367,0.3834,15.82,0.04068,1.668,0.04013,0.04014

['2025-09-22 14:12:15.558889',
 '2025-09-22 14:36:51.024951',
 '2025-09-22 15:13:32.437206',
 '2025-09-22 15:13:42.324450',
 '2025-09-22 15:13:44.929049',
 '2025-09-22 15:13:57.197217',
 '2025-09-22 15:14:04.108237',
 '2025-10-01 10:45:39.493475',
 '2025-10-01 10:45:43.572308',
 '2025-10-01 10:45:45.038490',
 '2025-10-01 10:45:45.870827',
 '2025-10-01 10:45:47.456667',
 '2025-10-01 10:45:49.275929',
 '2025-10-01 10:45:50.254635',
 '2025-10-01 10:45:51.168384',
 '2025-10-01 10:45:52.072152',
 '2025-10-01 10:45:52.998195',
 '2025-10-01 10:45:53.817472',
 '2025-10-01 10:45:54.834691',
 '2025-10-01 10:45:55.687214',
 '2025-10-01 10:53:32.732888',
 '2025-10-01 11:05:53.034961',
 '2025-10-01 11:06:03.214001',
 '2025-10-01 11:06:13.409766',
 '2025-10-01 11:06:23.615444',
 '2025-10-01 11:06:33.816770',
 '2025-10-01 11:06:43.976897',
 '2025-10-01 11:06:54.164687',
 '2025-10-01 11:07:04.324132',
 '2025-10-01 11:07:14.526111',
 '2025-10-01 11:07:24.709910',
 '2025-10-01 11:07:34.936393',
 '2025-10-01 11:07:45.100529',
 '2025-10-01 11:07:55.360115',
 '2025-10-01 11:08:05.536255',
 '2025-10-01 11:08:15.699199',
 '2025-10-01 11:08:25.890581',
 '2025-10-01 11:08:36.065507',
 '2025-10-01 11:08:46.212176',
 '2025-10-01 11:08:56.360178',
 '2025-10-01 11:09:06.545494',
 '2025-10-01 11:09:16.732794',
 '2025-10-01 11:09:26.874669',
 '2025-10-01 11:09:37.042067',
 '2025-10-01 11:09:47.210575',
 '2025-10-01 11:09:57.382201',
 '2025-10-01 11:10:07.535110',
 '2025-10-01 11:10:17.690720',
 '2025-10-01 11:10:27.850876',
 '2025-10-01 11:10:38.097263',
 '2025-10-01 11:10:48.275960',
 '2025-10-01 11:10:58.474196',
 '2025-10-01 11:11:08.609383',
 '2025-10-01 11:11:18.755025',
 '2025-10-01 11:11:28.888563',
 '2025-10-01 11:11:39.056709',
 '2025-10-01 11:11:49.191821',
 '2025-10-01 11:14:00.669660',
 '2025-10-01 11:14:11.330199',
 '2025-10-01 12:37:09.941490',
 '2025-10-01 12:37:20.414823',
 '2025-10-01 12:49:09.240350',
 '2025-10-01 12:49:19.558931',
 '2025-10-01 12:49:29.768361',
 '2025-10-01 12:49:39.943969',
 '2025-10-01 12:56:40.983929',
 '2025-10-01 12:56:51.322061',
 '2025-10-01 12:57:01.679620',
 '2025-10-01 12:57:11.875653',
 '2025-10-01 12:58:04.037209',
 '2025-10-01 12:58:14.405660',
 '2025-10-01 12:58:24.622651',
 '2025-10-01 12:58:34.853284',
 '2025-10-01 12:58:46.390962',
 '2025-10-01 12:58:56.586105',
 '2025-10-01 12:59:06.757927',
 '2025-10-01 12:59:16.924617',
 '2025-10-01 13:01:00.718376',
 '2025-10-01 13:01:11.232469',
 '2025-10-01 13:01:42.075645',
 '2025-10-01 13:01:52.443548',
 '2025-10-01 13:02:02.931495',
 '2025-10-01 13:02:13.111562',
 '2025-10-01 13:03:10.701921',
 '2025-10-01 13:03:21.083706',
 '2025-10-01 13:03:31.544246',
 '2025-10-01 13:03:42.660240',
 '2025-10-01 13:03:53.399241',
 '2025-10-01 13:04:04.793570',
 '2025-10-01 13:04:15.057347',
 '2025-10-01 13:04:25.279739',
 '2025-10-01 13:04:38.869161',
 '2025-10-01 13:04:49.501548',
 '2025-10-01 13:04:59.957084',
 '2025-10-01 13:05:10.399347',
 '2025-10-01 13:05:21.996818',
 '2025-10-01 13:05:32.198062',
 '2025-10-01 13:05:42.751156',
 '2025-10-01 13:05:53.092701',
 '2025-10-01 13:06:03.879166',
 '2025-10-01 13:06:14.711475',
 '2025-10-01 13:06:24.964406',
 '2025-10-01 13:06:37.947457',
 '2025-10-01 13:06:48.888449',
 '2025-10-01 13:07:00.697791',
 '2025-10-01 13:07:11.733244',
 '2025-10-01 13:07:21.994082',
 '2025-10-01 13:07:32.742785',
 '2025-10-01 13:07:42.993502',
 '2025-10-01 13:07:53.375453',
 '2025-10-01 13:08:05.647416',
 '2025-10-01 13:08:16.001365',
 '2025-10-01 13:08:50.876704',
 '2025-10-01 13:09:02.637033',
 '2025-10-01 13:09:13.391309',
 '2025-10-01 13:09:24.675636',
 '2025-10-01 13:09:35.939977',
 '2025-10-01 13:09:47.658174',
 '2025-10-01 13:09:58.898394',
 '2025-10-01 13:10:09.483793',
 '2025-10-01 13:10:24.809651',
 '2025-10-01 13:10:35.137401',
 '2025-10-01 13:10:45.930968',
 '2025-10-01 13:10:56.413773',
 '2025-10-01 13:11:06.673597',
 '2025-10-01 13:11:19.665754',
 '2025-10-01 13:11:29.928015',
 '2025-10-01 13:11:40.473656',
 '2025-10-01 13:11:50.608421',
 '2025-10-01 13:12:02.235946',
 '2025-10-01 13:12:12.508934',
 '2025-10-01 13:12:23.028914',
 '2025-10-01 13:12:34.221298',
 '2025-10-01 13:12:44.741413',
 '2025-10-01 13:12:56.744041',
 '2025-10-01 13:13:09.419102',
 '2025-10-01 13:13:20.121904',
 '2025-10-01 13:13:31.331059',
 '2025-10-01 13:13:41.697555',
 '2025-10-01 13:13:52.448531',
 '2025-10-01 13:14:02.975175',
 '2025-10-01 13:14:14.764309',
 '2025-10-01 13:14:25.006507',
 '2025-10-01 13:14:38.917103',
 '2025-10-01 13:14:56.407622',
 '2025-10-01 13:15:06.717935',
 '2025-10-01 13:15:16.955800',
 '2025-10-01 13:15:27.247958',
 '2025-10-01 13:15:40.355286',
 '2025-10-01 13:15:50.596524',
 '2025-10-01 13:16:01.026622',
 '2025-10-01 13:16:12.339518',
 '2025-10-01 13:16:22.584045',
 '2025-10-01 13:16:32.821317',
 '2025-10-01 13:16:45.769997',
 '2025-10-01 13:16:57.964636',
 '2025-10-01 13:17:09.329148',
 '2025-10-01 13:17:20.610012',
 '2025-10-01 13:17:32.050028',
 '2025-10-01 13:17:43.410994',
 '2025-10-01 13:17:53.675885',
 '2025-10-01 13:18:04.348068',
 '2025-10-01 13:18:14.659651',
 '2025-10-01 13:18:24.900409',
 '2025-10-01 13:18:35.794689',
 '2025-10-01 13:18:46.211239',
 '2025-10-01 13:18:56.425553',
 '2025-10-01 13:19:06.783184',
 '2025-10-01 13:19:17.085056',
 '2025-10-01 13:19:27.331126',
 '2025-10-01 13:19:37.700378',
 '2025-10-01 13:19:48.351050',
 '2025-10-01 13:19:58.557340',
 '2025-10-01 13:20:09.029776',
 '2025-10-01 13:20:19.241419',
 '2025-10-01 13:20:29.517433',
 '2025-10-01 13:20:39.704556',
 '2025-10-01 13:20:50.948142',
 '2025-10-01 13:21:01.313176',
 '2025-10-01 13:21:11.613412',
 '2025-10-01 13:21:21.855786',
 '2025-10-01 13:21:33.083827',
 '2025-10-01 13:21:44.912438',
 '2025-10-01 13:21:55.142309',
 '2025-10-01 13:22:05.450054',
 '2025-10-01 13:22:15.705951',
 '2025-10-01 13:22:26.290765',
 '2025-10-01 13:22:38.163255',
 '2025-10-01 13:22:48.687247',
 '2025-10-01 13:22:59.031961',
 '2025-10-01 13:23:09.681310',
 '2025-10-01 13:23:20.962303',
 '2025-10-01 13:23:32.003246',
 '2025-10-01 13:23:42.263401',
 '2025-10-01 13:23:54.560381',
 '2025-10-01 13:24:05.002567',
 '2025-10-01 13:24:15.170624',
 '2025-10-01 13:24:25.922627',
 '2025-10-01 13:24:36.165524',
 '2025-10-01 13:24:46.371683',
 '2025-10-01 13:24:56.617571',
 '2025-10-01 13:25:08.406880',
 '2025-10-01 13:25:19.146565',
 '2025-10-01 13:25:29.881586',
 '2025-10-01 13:25:41.210395',
 '2025-10-01 13:25:51.489172',
 '2025-10-01 13:26:01.764209',
 '2025-10-01 13:26:12.298378',
 '2025-10-01 13:26:23.818827',
 '2025-10-01 13:26:34.120249',
 '2025-10-01 13:26:46.147817',
 '2025-10-01 13:26:56.450598',
 '2025-10-01 13:27:07.221574',
 '2025-10-01 13:27:18.645990',
 '2025-10-01 13:27:28.857369',
 '2025-10-01 13:27:39.441597',
 '2025-10-01 13:27:51.090463',
 '2025-10-01 13:28:01.936914',
 '2025-10-01 13:28:12.556691',
 '2025-10-01 13:28:24.925590',
 '2025-10-01 13:28:46.113821',
 '2025-10-01 13:28:56.389367',
 '2025-10-01 13:29:06.635144',
 '2025-10-01 13:29:16.797774',
 '2025-10-01 13:29:27.019385',
 '2025-10-01 13:29:37.208837',
 '2025-10-01 13:29:47.422263',
 '2025-10-01 13:29:57.642338',
 '2025-10-01 13:30:07.913922',
 '2025-10-01 13:30:18.923490',
 '2025-10-01 13:30:29.172936',
 '2025-10-01 13:30:39.346667',
 '2025-10-01 13:30:49.582096',
 '2025-10-01 13:30:59.762285',
 '2025-10-01 13:31:10.786717',
 '2025-10-01 13:31:21.016715',
 '2025-10-01 13:31:31.237463',
 '2025-10-01 13:31:41.461164',
 '2025-10-01 13:31:51.643532',
 '2025-10-01 13:32:01.901981',
 '2025-10-01 13:32:12.087438',
 '2025-10-01 13:32:22.279150',
 '2025-10-01 13:32:32.572196',
 '2025-10-01 13:32:42.822490',
 '2025-10-01 13:32:53.029157',
 '2025-10-01 13:33:03.211948',
 '2025-10-01 13:33:13.463893',
 '2025-10-01 13:33:23.701004',
 '2025-10-01 13:33:33.913546',
 '2025-10-01 13:33:44.113127',
 '2025-10-01 13:33:54.374315',
 '2025-10-01 13:34:04.610927',
 '2025-10-01 13:34:14.850592',
 '2025-10-01 13:34:26.045440',
 '2025-10-01 13:34:36.293358',
 '2025-10-01 13:34:47.571650',
 '2025-10-01 13:34:57.775492',
 '2025-10-01 13:35:07.933643',
 '2025-10-01 13:35:18.186738',
 '2025-10-01 13:35:28.366454',
 '2025-10-01 13:35:38.655016',
 '2025-10-01 13:35:48.893636',
 '2025-10-01 13:35:59.098769',
 '2025-10-01 13:36:09.882646',
 '2025-10-01 13:36:20.036468',
 '2025-10-01 13:36:30.269257',
 '2025-10-01 13:36:40.489256',
 '2025-10-01 13:36:50.718234',
 '2025-10-01 13:37:01.110668',
 '2025-10-01 13:37:11.411710',
 '2025-10-01 13:37:21.743296',
 '2025-10-01 13:37:32.121223',
 '2025-10-01 13:37:43.969770',
 '2025-10-01 13:37:55.211108',
 '2025-10-01 13:38:05.657038',
 '2025-10-01 13:38:15.945904',
 '2025-10-01 13:38:26.181725',
 '2025-10-01 13:38:36.360144',
 '2025-10-01 13:38:46.586393',
 '2025-10-01 13:38:56.780004',
 '2025-10-01 13:39:07.087226',
 '2025-10-01 13:39:17.347125',
 '2025-10-01 13:39:27.670443',
 '2025-10-01 13:39:37.867455',
 '2025-10-01 13:39:48.084486',
 '2025-10-01 13:39:59.267538',
 '2025-10-01 13:40:09.474729',
 '2025-10-01 13:40:20.656316',
 '2025-10-01 13:40:34.649766',
 '2025-10-01 13:40:45.254575',
 '2025-10-01 13:40:59.712065',
 '2025-10-01 13:41:10.082852',
 '2025-10-01 13:41:20.291895',
 '2025-10-01 13:41:30.490775',
 '2025-10-01 13:41:40.706153',
 '2025-10-01 13:41:51.067127',
 '2025-10-01 13:42:01.263140',
 '2025-10-01 13:42:11.553119',
 '2025-10-01 13:42:21.761381',
 '2025-10-01 13:42:31.931921',
 '2025-10-01 13:42:42.143594',
 '2025-10-01 13:42:52.371035',
 '2025-10-01 13:43:02.726999',
 '2025-10-01 13:43:13.880435',
 '2025-10-01 13:43:24.105627',
 '2025-10-01 13:43:34.339070',
 '2025-10-01 13:43:45.026551',
 '2025-10-01 13:43:56.400713',
 '2025-10-01 13:44:06.603920',
 '2025-10-01 13:44:16.836731',
 '2025-10-01 13:44:27.093049',
 '2025-10-01 13:44:38.151588',
 '2025-10-01 13:44:48.549378',
 '2025-10-01 13:44:59.719071',
 '2025-10-01 13:45:10.007752',
 '2025-10-01 13:45:20.264675',
 '2025-10-01 13:45:30.452701',
 '2025-10-01 13:45:40.618098',
 '2025-10-01 13:45:50.868576',
 '2025-10-01 13:46:01.108870',
 '2025-10-01 13:46:11.280885',
 '2025-10-01 13:46:21.475241',
 '2025-10-01 13:46:32.007263',
 '2025-10-01 13:46:42.367345',
 '2025-10-01 13:46:52.801649',
 '2025-10-01 13:47:02.989589',
 '2025-10-01 13:47:13.225556',
 '2025-10-01 13:47:23.415248',
 '2025-10-01 13:47:33.650674',
 '2025-10-01 13:47:43.851762',
 '2025-10-01 13:47:54.050275',
 '2025-10-01 13:48:04.289229',
 '2025-10-01 13:48:14.564471',
 '2025-10-01 13:48:24.735297',
 '2025-10-01 13:48:35.055762',
 '2025-10-01 13:48:45.342586',
 '2025-10-01 13:51:01.814084',
 '2025-10-01 13:51:12.052787',
 '2025-10-01 13:51:22.262342',
 '2025-10-01 13:51:32.453141',
 '2025-10-01 13:51:42.647759',
 '2025-10-01 13:51:52.890150',
 '2025-10-01 13:52:03.308548',
 '2025-10-01 13:52:13.520874',
 '2025-10-01 13:52:23.903267',
 '2025-10-01 13:52:34.125014',
 '2025-10-01 13:52:44.343105',
 '2025-10-01 13:52:54.637563',
 '2025-10-01 13:53:05.112972',
 '2025-10-01 13:53:16.986896',
 '2025-10-01 13:53:27.182285',
 '2025-10-01 13:53:37.379900',
 '2025-10-01 13:53:48.195805',
 '2025-10-01 13:53:58.406859',
 '2025-10-01 13:54:08.603267',
 '2025-10-01 13:54:18.796101',
 '2025-10-01 13:54:29.541571',
 '2025-10-01 13:54:39.792576',
 '2025-10-01 13:54:50.643344',
 '2025-10-01 13:55:00.829763',
 '2025-10-01 13:55:10.990000',
 '2025-10-01 13:55:21.241883',
 '2025-10-01 13:55:38.515021',
 '2025-10-01 13:55:48.750552',
 '2025-10-01 13:55:58.965872',
 '2025-10-01 13:56:09.203834',
 '2025-10-01 13:56:19.419992',
 '2025-10-01 13:56:29.623637',
 '2025-10-01 13:56:39.802846',
 '2025-10-01 13:56:50.681730',
 '2025-10-01 13:57:00.877404',
 '2025-10-01 13:57:11.062187',
 '2025-10-01 13:57:21.299217',
 '2025-10-01 13:57:31.511612',
 '2025-10-01 13:57:41.763079',
 '2025-10-01 13:57:51.972224',
 '2025-10-01 13:58:02.187034',
 '2025-10-01 13:58:12.380293',
 '2025-10-01 13:58:22.570603',
 '2025-10-01 13:58:32.771173',
 '2025-10-01 13:58:42.976881',
 '2025-10-01 13:58:53.158393',
 '2025-10-01 13:59:03.426331',
 '2025-10-01 13:59:13.927546',
 '2025-10-01 13:59:24.232125',
 '2025-10-01 13:59:34.497435',
 '2025-10-01 13:59:44.699293',
 '2025-10-01 13:59:54.936421',
 '2025-10-01 14:00:06.280565',
 '2025-10-01 14:00:16.466552',
 '2025-10-01 14:00:27.399529',
 '2025-10-01 14:00:37.651086',
 '2025-10-01 14:00:47.816086',
 '2025-10-01 14:00:58.111305',
 '2025-10-01 14:01:08.314185',
 '2025-10-01 14:01:19.425577',
 '2025-10-01 14:01:29.593373',
 '2025-10-01 14:01:39.800757',
 '2025-10-01 14:01:50.493054',
 '2025-10-01 14:02:00.757643',
 '2025-10-01 14:02:10.991224',
 '2025-10-01 14:02:21.247387',
 '2025-10-01 14:02:32.617962',
 '2025-10-01 14:02:42.768009',
 '2025-10-01 14:02:52.955200',
 '2025-10-01 14:03:03.297201',
 '2025-10-01 14:03:13.452838',
 '2025-10-01 14:03:23.624686',
 '2025-10-01 14:03:33.827172',
 '2025-10-01 14:03:43.990883',
 '2025-10-01 14:03:55.037054',
 '2025-10-01 14:04:05.342690',
 '2025-10-01 14:04:15.571586',
 '2025-10-01 14:04:26.836788',
 '2025-10-01 14:04:37.657032',
 '2025-10-01 14:04:48.032160',
 '2025-10-01 14:04:58.238890',
 '2025-10-01 14:05:09.328664',
 '2025-10-01 14:05:19.485723',
 '2025-10-01 14:05:29.757918',
 '2025-10-01 14:05:40.586546',
 '2025-10-01 14:05:50.782606',
 '2025-10-01 14:06:00.992161',
 '2025-10-01 14:06:11.319267',
 '2025-10-01 14:06:21.640689',
 '2025-10-01 14:06:31.920840',
 '2025-10-01 14:06:43.601337',
 '2025-10-01 14:06:53.842535',
 '2025-10-01 14:07:04.126174',
 '2025-10-01 14:07:14.470784',
 '2025-10-01 14:07:24.649428',
 '2025-10-01 14:07:34.848242',
 '2025-10-01 14:07:45.046466',
 '2025-10-01 14:07:55.223404',
 '2025-10-01 14:08:05.474700',
 '2025-10-01 14:08:15.629105',
 '2025-10-01 14:08:25.861715',
 '2025-10-01 14:08:36.019987',
 '2025-10-01 14:08:46.212422',
 '2025-10-01 14:08:56.486851',
 '2025-10-01 14:09:06.650957',
 '2025-10-01 14:09:16.802246',
 '2025-10-01 14:09:26.976667',
 '2025-10-01 14:09:37.264569',
 '2025-10-01 14:09:47.836836',
 '2025-10-01 14:09:58.134845',
 '2025-10-01 14:10:08.303100',
 '2025-10-01 14:10:18.481116',
 '2025-10-01 14:10:28.656297',
 '2025-10-01 14:10:38.855716',
 '2025-10-01 14:10:49.102556',
 '2025-10-01 14:10:59.477832',
 '2025-10-01 14:11:09.709172',
 '2025-10-01 14:11:19.919735',
 '2025-10-01 14:11:30.134047',
 '2025-10-01 14:11:40.373425',
 '2025-10-01 14:11:50.611844',
 '2025-10-01 14:12:00.892785',
 '2025-10-01 14:12:11.075561',
 '2025-10-01 14:12:21.327686',
 '2025-10-01 14:12:31.518128',
 '2025-10-01 14:12:41.717979',
 '2025-10-01 14:12:51.929024',
 '2025-10-01 14:13:02.161661',
 '2025-10-01 14:13:12.368222',
 '2025-10-01 14:13:23.377825',
 '2025-10-01 14:13:33.698010',
 '2025-10-01 14:13:43.849996',
 '2025-10-01 14:13:54.070803',
 '2025-10-01 14:14:04.270562',
 '2025-10-01 14:14:14.522067',
 '2025-10-01 14:14:24.670699',
 '2025-10-01 14:14:34.849387',
 '2025-10-01 14:14:45.086344',
 '2025-10-01 14:14:55.227791',
 '2025-10-01 14:15:05.510589',
 '2025-10-01 14:15:15.725528',
 '2025-10-01 14:15:25.992591',
 '2025-10-01 14:15:37.089128',
 '2025-10-01 14:15:47.323863',
 '2025-10-01 14:15:57.503631',
 '2025-10-01 14:16:07.675637',
 '2025-10-01 14:16:17.835197',
 '2025-10-01 14:16:28.007991',
 '2025-10-01 14:16:38.264094',
 '2025-10-01 14:16:48.450691',
 '2025-10-01 14:17:00.390513',
 '2025-10-01 14:17:10.556151',
 '2025-10-01 14:17:20.728340',
 '2025-10-01 14:17:30.873986',
 '2025-10-01 14:17:41.150175',
 '2025-10-01 14:17:52.221574',
 '2025-10-01 14:18:02.435009',
 '2025-10-01 14:18:12.742458',
 '2025-10-01 14:18:22.932925',
 '2025-10-01 14:18:33.114449',
 '2025-10-01 14:18:43.339145',
 '2025-10-01 14:18:53.546054',
 '2025-10-01 14:19:03.704265',
 '2025-10-01 14:19:13.978538',
 '2025-10-01 14:19:24.142380',
 '2025-10-01 14:19:34.425181',
 '2025-10-01 14:19:44.619160',
 '2025-10-01 14:19:54.927963',
 '2025-10-01 14:20:05.276011',
 '2025-10-01 14:20:15.493809',
 '2025-10-01 14:20:25.721048',
 '2025-10-01 14:20:35.902470',
 '2025-10-01 14:20:46.170036',
 '2025-10-01 14:20:56.625168',
 '2025-10-01 14:21:06.803158',
 '2025-10-01 14:21:16.969813',
 '2025-10-01 14:21:27.164136',
 '2025-10-01 14:21:37.450741',
 '2025-10-01 14:21:47.723252',
 '2025-10-01 14:21:57.928662',
 '2025-10-01 14:22:08.130831',
 '2025-10-01 14:22:18.336567',
 '2025-10-01 14:22:28.501906',
 '2025-10-01 14:22:38.691019',
 '2025-10-01 14:22:48.882797',
 '2025-10-01 14:22:59.063221',
 '2025-10-01 14:23:09.225160',
 '2025-10-01 14:23:19.398622',
 '2025-10-01 14:23:29.553474',
 '2025-10-01 14:23:39.765407',
 '2025-10-01 14:23:49.932264',
 '2025-10-01 14:24:00.076277',
 '2025-10-01 14:24:10.241738',
 '2025-10-01 14:24:20.408158',
 '2025-10-01 14:24:30.618334',
 '2025-10-01 14:24:40.793831',
 '2025-10-01 14:24:50.973557',
 '2025-10-01 14:25:01.134728',
 '2025-10-01 14:25:11.351235',
 '2025-10-01 14:25:21.581224',
 '2025-10-01 14:25:31.790154',
 '2025-10-01 14:25:41.960473',
 '2025-10-01 14:25:52.410942',
 '2025-10-01 14:26:02.640203',
 '2025-10-01 14:26:12.779853',
 '2025-10-01 14:26:22.939953',
 '2025-10-01 14:26:33.108222',
 '2025-10-01 14:26:43.319676',
 '2025-10-01 14:26:53.532287',
 '2025-10-01 14:27:03.694067',
 '2025-10-01 14:27:13.840422',
 '2025-10-01 14:27:24.051698',
 '2025-10-01 14:27:34.206853',
 '2025-10-01 14:27:44.375922',
 '2025-10-01 14:27:54.561063',
 '2025-10-01 14:28:04.787160',
 '2025-10-01 14:28:14.968666',
 '2025-10-01 14:28:25.141533',
 '2025-10-01 14:28:35.449611',
 '2025-10-01 14:28:45.642732',
 '2025-10-01 14:28:56.669609',
 '2025-10-01 14:29:06.862705',
 '2025-10-01 14:29:17.022230',
 '2025-10-01 14:29:27.169223',
 '2025-10-01 14:29:37.356759',
 '2025-10-01 14:29:47.528305',
 '2025-10-01 14:29:57.708093',
 '2025-10-01 14:30:07.896646',
 '2025-10-01 14:30:18.075801',
 '2025-10-01 14:30:28.219179',
 '2025-10-01 14:30:38.369753',
 '2025-10-01 14:30:48.546908',
 '2025-10-01 14:30:58.718607',
 '2025-10-01 14:31:09.004439',
 '2025-10-01 14:31:19.174669',
 '2025-10-01 14:31:29.394580',
 '2025-10-01 14:31:39.544309',
 '2025-10-01 14:31:49.703785',
 '2025-10-01 14:31:59.876067',
 '2025-10-01 14:32:10.051767',
 '2025-10-01 14:32:20.206936',
 '2025-10-01 14:32:30.693065',
 '2025-10-01 14:32:40.850323',
 '2025-10-01 14:32:51.097422',
 '2025-10-01 14:33:01.293988',
 '2025-10-01 14:33:11.528470',
 '2025-10-01 14:33:22.647299',
 '2025-10-01 14:33:32.786961',
 '2025-10-01 14:33:42.962837',
 '2025-10-01 14:33:53.114046',
 '2025-10-01 14:34:03.321427',
 '2025-10-01 14:34:13.518566',
 '2025-10-01 14:34:23.672468',
 '2025-10-01 14:34:33.836959',
 '2025-10-01 14:34:44.083674',
 '2025-10-01 14:34:54.255231',
 '2025-10-01 14:35:04.453716',
 '2025-10-01 14:35:14.702083',
 '2025-10-01 14:35:24.912298',
 '2025-10-01 14:35:35.169248',
 '2025-10-01 14:35:45.438651',
 '2025-10-01 14:35:55.615949',
 '2025-10-01 14:36:05.874679',
 '2025-10-01 14:36:16.037648',
 '2025-10-01 14:36:26.199891',
 '2025-10-01 14:36:36.346366',
 '2025-10-01 14:36:46.510594',
 '2025-10-01 14:36:57.510595',
 '2025-10-01 14:37:07.677262',
 '2025-10-01 14:37:17.851230',
 '2025-10-01 14:37:28.014948',
 '2025-10-01 14:37:38.251024',
 '2025-10-01 14:37:48.477189',
 '2025-10-01 14:37:58.684835',
 '2025-10-01 14:38:08.853674',
 '2025-10-01 14:38:19.026316',
 '2025-10-01 14:38:29.233392',
 '2025-10-01 14:38:39.413020',
 '2025-10-01 14:38:49.611891',
 '2025-10-01 14:38:59.790683',
 '2025-10-01 14:39:10.027357',
 '2025-10-01 14:39:20.175964',
 '2025-10-01 14:39:30.370704',
 '2025-10-01 14:39:40.553317',
 '2025-10-01 14:39:50.728831',
 '2025-10-01 14:40:01.012561',
 '2025-10-01 14:40:11.182454',
 '2025-10-01 14:40:21.360614',
 '2025-10-01 14:40:31.532582',
 '2025-10-01 14:40:41.684862',
 '2025-10-01 14:40:51.837225',
 '2025-10-01 14:41:01.970206',
 '2025-10-01 14:41:12.159170',
 '2025-10-01 14:41:22.370267',
 '2025-10-01 14:41:32.543454',
 '2025-10-01 14:41:42.751628',
 '2025-10-01 14:41:52.952640',
 '2025-10-01 14:42:03.137305',
 '2025-10-01 14:42:13.360463',
 '2025-10-01 14:42:23.600436',
 '2025-10-01 14:42:33.770300',
 '2025-10-01 14:42:43.978348',
 '2025-10-01 14:42:54.185132',
 '2025-10-01 14:43:04.348816',
 '2025-10-01 14:43:14.518202',
 '2025-10-01 14:43:24.710946',
 '2025-10-01 14:43:34.911910',
 '2025-10-01 14:43:45.077472',
 '2025-10-01 14:43:55.249360',

In [23]:
row = get_df_binance_at_present()
row

,ETHBTC,LTCBTC,BNBBTC,NEOBTC,QTUMETH,EOSETH,SNTETH,BNTETH,BCCBTC,GASBTC,...,SNXUSDC,EDENUSDT,EDENUSDC,EDENBNB,EDENFDUSD,EDENTRY,NOMFDUSD,NOMTRY,NOMUSDC,NOMUSDT
datetime,,,,,,,,,,,,,,,,,,,,,
2025-10-02 16:06:28.125001,0.03713000,0.00099600,0.00874900,0.00005190,0.00051600,0.00030670,0.00001700,0.00020260,0.00000000,0.00002640,...,1.29000000,0.38000000,0.38060000,0.00036420,0.37950000,15.79000000,0.04020000,1.67400000,0.04032000,0.04030000

In [24]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

,0GBNB,0GFDUSD,0GTRY,0GUSDC,0GUSDT,1000CATBNB,1000CATFDUSD,1000CATTRY,1000CATUSDC,1000CATUSDT,...,ZROBTC,ZROFDUSD,ZROTRY,ZROUSDC,ZROUSDT,ZRXBNB,ZRXBTC,ZRXBUSD,ZRXETH,ZRXUSDT
2025-10-02 16:12:42.645693,0.00260539,2.70800000,112.10000000,2.70300000,2.70000000,0.00000870,0.00770000,0.31900000,0.00768000,0.00767000,...,0.00001989,2.36400000,98.10000000,2.35900000,2.35800000,0.00000000,0.00000216,0.16890000,0.00009940,0.25540000
2025-10-02 16:12:44.138805,0.00260539,2.70800000,112.10000000,2.70300000,2.70000000,0.00000870,0.00770000,0.31900000,0.00768000,0.00767000,...,0.00001989,2.36400000,98.10000000,2.35900000,2.35800000,0.00000000,0.00000216,0.16890000,0.00009940,0.25540000
2025-10-02 16:12:46.269058,0.00260539,2.70800000,112.19000000,2.70300000,2.69900000,0.00000870,0.00770000,0.31900000,0.00768000,0.00767000,...,0.00001989,2.36400000,98.10000000,2.35900000,2.35800000,0.00000000,0.00000216,0.16890000,0.00009940,0.25540000
2025-10-02 16:12:47.197609,0.00260539,2.70800000,112.19000000,2.70300000,2.69900000,0.00000870,0.00770000,0.31900000,0.00768000,0.00767000,...,0.00001989,2.36400000,98.10000000,2.36100000,2.35800000,0.00000000,0.00000216,0.16890000,0.00009940,0.25540000
2025-10-02 16:12:47.984289,0.00260539,2.70800000,112.19000000,2.70300000,2.69900000,0.00000870,0.00770000,0.31900000,0.00768000,0.00767000,...,0.00001989,2.36400000,98.10000000,2.36100000,2.35800000,0.00000000,0.00000216,0.16890000,0.00009940,0.25540000
2025-10-02 16:12:48.837274,0.00260539,2.70800000,112.19000000,2.70300000,2.69900000,0.00000870,0.00770000,0.31900000,0.00768000,0.00767000,...,0.00001989,2.36400000,98.10000000,2.36100000,2.35700000,0.00000000,0.00000216,0.16890000,0.00009940,0.25540000
2025-10-02 16:12:49.652399,0.00260539,2.70800000,112.19000000,2.70300000,2.69900000,0.00000870,0.00770000,0.31900000,0.00768000,0.00767000,...,0.00001989,2.36400000,98.10000000,2.36100000,2.35700000,0.00000000,0.00000216,0.16890000,0.00009940,0.25540000
2025-10-02 16:13:17.973959,0.00260539,2.70800000,112.23000000,2.70400000,2.70200000,0.00000870,0.00770000,0.31900000,0.00768000,0.00767000,...,0.00001989,2.36400000,97.90000000,2.35900000,2.35700000,0.00000000,0.00000216,0.16890000,0.00009940,0.25540000
2025-10-02 16:13:19.288940,0.00260539,2.70800000,112.23000000,2.70400000,2.70200000,0.00000870,0.00770000,0.31900000,0.00768000,0.00767000,...,0.00001989,2.36400000,97.90000000,2.35900000,2.35700000,0.00000000,0.00000216,0.16890000,0.00009940,0.25540000
2025-10-02 16:13:20.190384,0.00260539,2.70800000,112.23000000,2.70400000,2.70200000,0.00000870,0.00770000,0.31900000,0.00768000,0.00767000,...,0.00001989,2.36400000,97.90000000,2.35900000,2.35700000,0.00000000,0.00000216,0.16890000,0.00009940,0.25540000
2025-10-02 16:13:21.029688,0.00260539,2.70800000,112.31000000,2.70400000,2.70200000,0.00000870,0.00770000,0.31900000,0.00768000,0.00767000,...,0.00001989,2.36400000,97.90000000,2.35900000,2.35700000,0.00000000,0.00000216,0.16890000,0.00009940,0.25540000
2025-10-02 16:13:21.764794,0.00260539,2.70800000,112.31000000,2.70400000,2.70200000,0.00000870,0.00770000,0.31900000,0.00768000,0.00767000,...,0.00001989,2.36400000,97.90000000,2.35900000,2.35700000,0.00000000,0.00000216,0.16890000,0.00009940,0.25540000
2025-10-02 16:13:22.529293,0.00260539,2.70800000,112.31000000,2.70400000,2.70200000,0.00000870,0.00770000,0.31900000,0.00768000,0.00767000,...,0.00001989,2.36400000,97.90000000,2.35900000,2.35700000,0.00000000,0.00000216,0.16890000,0.00009940,0.25540000
2025-10-02 16:13:23.317653,0.00260539,2.70800000,112.31000000,2.70400000,2.70200000,0.00000870,0.00770000,0.31900000,0.00768000,0.00767000,...,0.00001989,2.36400000,97.90000000,2.35900000,2.35700000,0.00000000,0.00000216,0.16890000,0.00009940,0.25540000
2025-10-02 16:13:24.319660,0.00260539,2.70800000,112.31000000,2.70400000,2.70200000,0.00000870,0.00770000,0.31900000,0.00768000,0.00767000,...,0.00001989,2.36400000,97.90000000,2.35800000,2.35700000,0.00000000,0.00000216,0.16890000,0.00009940,0.25540000
2025-10-02 16:13:25.210240,0.00260539,2.70800000,112.31000000,2.70400000,2.70200000,0.00000870,0.00770000,0.31900000,0.00768000,0.00767000,...,0.00001989,2.36400000,97.90000000,2.35800000,2.35700000,0.00000000,0.00000216,0.16890000,0.00009940,0.25540000
2025-10-02 16:13:25.978789,0.00260539,2.70800000,112.31000000,2.70400000,2.70200000,0.00000870,0.00770000,0.31900000,0.00768000,0.00767000,...,0.00001989,2.36400000,97.90000000,2.35800000,2.35600000,0.00000000,0.00000216,0.16890000,0.00009940,0.25540000
2025-10-02 16:13:26.647025,0.00260539,2.70800000,112.31000000,2.70400000,2.70200000,0.00000870,0.00770000,0.31900000,0.00768000,0.00767000,...,0.00001989,2.36400000,97.90000000,2.35900000,2.35600000,0.00000000,0.00000216,0.16890000,0.00009940,0.25540000